"""Artifacts data for Apex."""

from __future__ import annotations

from typing import Dict

_FINDING_ARTIFACT_MAP: Dict[str, Dict] = {
    "git head": {
        "produces": ["PARTIAL_SOURCE", "FILE_READ_LIMITED"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "RECON",
        "effort": 1,
        "label": "Git Repository Exposed",
    },
    "source map exposure": {
        "produces": ["PARTIAL_SOURCE"],
        "requires": [],
        "terminal": False,
        "severity": "MED",
        "mitre_stage": "RECON",
        "effort": 1,
        "label": "Source Map Exposed",
    },
    "js file secrets": {
        "produces": ["CREDENTIALS", "SIGNING_KEY"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 1,
        "label": "Secrets in JS",
    },
    "partial_source": {
        "produces": ["CREDENTIALS", "SIGNING_KEY", "SCHEMA_KNOWLEDGE"],
        "requires": ["PARTIAL_SOURCE"],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 1,
        "label": "Source Code Analysis",
        "is_artifact_node": True,
    },
    "jwt weak secret": {
        "produces": ["SIGNING_KEY"],
        "requires": [],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 1,
        "label": "JWT Weak Secret",
    },
    "signing_key": {
        "produces": ["ADMIN_SESSION", "ACCOUNT_TAKEOVER"],
        "requires": ["SIGNING_KEY"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "PRIVILEGE_ESCALATION",
        "effort": 1,
        "label": "Token Forge",
        "is_artifact_node": True,
    },
    "jwt algorithm confusion": {
        "produces": ["CRYPTO_MATERIAL", "AUTH_CONFUSION"],
        "requires": [],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 2,
        "label": "JWT Algorithm Confusion",
    },
    "crypto_material + auth_confusion": {
        "produces": ["SIGNING_KEY"],
        "requires": ["CRYPTO_MATERIAL", "AUTH_CONFUSION"],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 1,
        "label": "RS256->HS256 Key Confusion",
        "is_artifact_node": True,
    },
    "ssrf param echo": {
        "produces": ["SSRF_PRIMITIVE"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "INITIAL_ACCESS",
        "effort": 1,
        "label": "SSRF",
    },
    "cloud metadata ssrf": {
        "produces": ["CLOUD_CREDS", "INTERNAL_NETWORK"],
        "requires": ["SSRF_PRIMITIVE"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 1,
        "label": "IMDS via SSRF",
    },
    "gcp metadata ssrf": {
        "produces": ["CLOUD_CREDS"],
        "requires": ["SSRF_PRIMITIVE"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 1,
        "label": "GCP IMDS",
    },
    "redis unauth": {
        "produces": ["CODE_EXEC", "CREDENTIALS"],
        "requires": ["SSRF_PRIMITIVE"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "LATERAL_MOVEMENT",
        "effort": 2,
        "label": "Redis RCE via SSRF",
    },
    "lfi": {
        "produces": ["FILE_READ_LIMITED"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "INITIAL_ACCESS",
        "effort": 1,
        "label": "LFI",
    },
    "lfi log poisoning": {
        "produces": ["CODE_EXEC"],
        "requires": ["FILE_READ_LIMITED"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 2,
        "label": "Log Poisoning RCE",
    },
    "file_read_limited": {
        "produces": ["NETWORK_TOPOLOGY", "CREDENTIALS", "SSRF_PRIMITIVE"],
        "requires": ["FILE_READ_LIMITED"],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "DISCOVERY",
        "effort": 1,
        "label": "Internal File Analysis",
        "is_artifact_node": True,
    },
    "ssti engine fingerprint": {
        "produces": ["TEMPLATE_EXEC"],
        "requires": [],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 1,
        "label": "SSTI",
    },
    "ssti": {
        "produces": ["TEMPLATE_EXEC"],
        "requires": [],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 1,
        "label": "SSTI",
    },
    "template_exec": {
        "produces": ["CODE_EXEC"],
        "requires": ["TEMPLATE_EXEC"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 1,
        "label": "Template RCE",
        "is_artifact_node": True,
    },
    "command injection": {
        "produces": ["CODE_EXEC"],
        "requires": [],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 1,
        "label": "CMDi",
    },
    "sqli error": {
        "produces": ["INTERNAL_STATE", "SCHEMA_KNOWLEDGE", "CREDENTIALS"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "INITIAL_ACCESS",
        "effort": 1,
        "label": "SQLi",
    },
    "sqli blind timing": {
        "produces": ["SCHEMA_KNOWLEDGE", "CREDENTIALS"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "INITIAL_ACCESS",
        "effort": 2,
        "label": "Blind SQLi",
    },
    "schema_knowledge": {
        "produces": ["DB_ACCESS"],
        "requires": ["SCHEMA_KNOWLEDGE", "CREDENTIALS"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "COLLECTION",
        "effort": 2,
        "label": "DB Enumeration",
        "is_artifact_node": True,
    },
    "xxe xml post": {
        "produces": ["FILE_READ_LIMITED", "SSRF_PRIMITIVE"],
        "requires": [],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "INITIAL_ACCESS",
        "effort": 1,
        "label": "XXE",
    },
    "subdomain takeover": {
        "produces": ["DNS_CONTROL"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "RESOURCE_DEV",
        "effort": 2,
        "label": "Subdomain Takeover",
    },
    "dns_control": {
        "produces": ["SESSION_TOKEN", "ACCOUNT_TAKEOVER"],
        "requires": ["DNS_CONTROL", "SESSION_TOKEN"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "PRIVILEGE_ESCALATION",
        "effort": 2,
        "label": "Cookie Theft via Subdomain",
        "is_artifact_node": True,
    },
    "cookie flags": {
        "produces": ["SESSION_TOKEN"],
        "requires": [],
        "terminal": False,
        "severity": "MED",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 2,
        "label": "Insecure Cookie",
    },
    "xss": {
        "produces": ["SESSION_TOKEN", "STORED_PAYLOAD"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "INITIAL_ACCESS",
        "effort": 2,
        "label": "XSS",
    },
    "stored_payload": {
        "produces": ["PERSISTENT_XSS", "SESSION_TOKEN", "ACCOUNT_TAKEOVER"],
        "requires": ["STORED_PAYLOAD"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "COLLECTION",
        "effort": 2,
        "label": "Stored XSS Execution",
        "is_artifact_node": True,
    },
    "open redirect": {
        "produces": ["AUTH_CONFUSION"],
        "requires": [],
        "terminal": False,
        "severity": "MED",
        "mitre_stage": "INITIAL_ACCESS",
        "effort": 1,
        "label": "Open Redirect",
    },
    "oauth state param": {
        "produces": ["AUTH_CONFUSION", "SESSION_TOKEN"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "INITIAL_ACCESS",
        "effort": 2,
        "label": "OAuth State Missing",
    },
    "auth_confusion + session_token": {
        "produces": ["ACCOUNT_TAKEOVER"],
        "requires": ["AUTH_CONFUSION", "SESSION_TOKEN"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "PRIVILEGE_ESCALATION",
        "effort": 2,
        "label": "OAuth Token Theft",
        "is_artifact_node": True,
    },
    "cors arbitrary origin": {
        "produces": ["AUTH_CONFUSION", "MASS_DATA_EXFIL"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "COLLECTION",
        "effort": 2,
        "label": "CORS Arbitrary Origin",
    },
    "graphql introspection": {
        "produces": ["SCHEMA_KNOWLEDGE"],
        "requires": [],
        "terminal": False,
        "severity": "MED",
        "mitre_stage": "RECON",
        "effort": 1,
        "label": "GraphQL Introspection",
    },
    "config yaml exposed": {
        "produces": ["CREDENTIALS", "INTERNAL_STATE"],
        "requires": [],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 1,
        "label": "Config Exposed",
    },
    "db admin files": {
        "produces": ["DB_ACCESS"],
        "requires": ["CREDENTIALS"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "COLLECTION",
        "effort": 1,
        "label": "DB Admin Access",
    },
    "deserialization surface": {
        "produces": ["DESERIALIZATION_EXEC"],
        "requires": [],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 3,
        "label": "Deserialization",
    },
    "deserialization_exec": {
        "produces": ["CODE_EXEC"],
        "requires": ["DESERIALIZATION_EXEC"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 2,
        "label": "Deserialization RCE",
        "is_artifact_node": True,
    },
    "file upload surface": {
        "produces": ["CODE_EXEC", "STORED_PAYLOAD"],
        "requires": [],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 2,
        "label": "File Upload RCE",
    },
    "prototype pollution server": {
        "produces": ["DESERIALIZATION_EXEC", "CODE_EXEC"],
        "requires": [],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 3,
        "label": "SSPP",
    },
    "password reset poisoning": {
        "produces": ["ACCOUNT_TAKEOVER"],
        "requires": [],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 2,
        "label": "Password Reset Poisoning",
    },
    "default credentials": {
        "produces": ["CREDENTIALS", "ADMIN_SESSION"],
        "requires": [],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "INITIAL_ACCESS",
        "effort": 1,
        "label": "Default Credentials",
    },
    "mass assignment": {
        "produces": ["PARAM_CONTROL", "ADMIN_SESSION"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "PRIVILEGE_ESCALATION",
        "effort": 1,
        "label": "Mass Assignment",
    },
    "idor probe": {
        "produces": ["MASS_DATA_EXFIL", "ACCOUNT_TAKEOVER"],
        "requires": [],
        "terminal": True,
        "severity": "HIGH",
        "mitre_stage": "COLLECTION",
        "effort": 1,
        "label": "IDOR",
    },
    "jwt kid injection": {
        "produces": ["AUTH_CONFUSION", "SIGNING_KEY"],
        "requires": [],
        "terminal": False,
        "severity": "CRIT",
        "mitre_stage": "CREDENTIAL_ACCESS",
        "effort": 2,
        "label": "JWT kid SQLi",
    },
    "behavioral matrix": {
        "produces": ["PARAM_CONTROL", "AUTH_CONFUSION"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "RECON",
        "effort": 1,
        "label": "BCM",
    },
    "param_control + auth_confusion": {
        "produces": ["ADMIN_SESSION", "ACCOUNT_TAKEOVER"],
        "requires": ["PARAM_CONTROL", "AUTH_CONFUSION"],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "PRIVILEGE_ESCALATION",
        "effort": 2,
        "label": "Parameter Privilege Escalation",
        "is_artifact_node": True,
    },
    "ai prompt injection": {
        "produces": ["CODE_EXEC", "MASS_DATA_EXFIL", "SSRF_PRIMITIVE"],
        "requires": [],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 2,
        "label": "LLM Prompt Injection",
    },
    "rag poisoning": {
        "produces": ["MASS_DATA_EXFIL", "STORED_PAYLOAD"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "COLLECTION",
        "effort": 2,
        "label": "RAG Poisoning",
    },
    "ANY_ZERO": {
        "produces": ["CODE_EXEC", "FILE_READ_ARBITRARY"],
        "requires": [],
        "terminal": True,
        "severity": "CRIT",
        "mitre_stage": "EXECUTION",
        "effort": 1,
        "label": "Zero-Day Exploit",
    },
    "app model synthesis": {
        "produces": ["PARAM_CONTROL", "AUTH_CONFUSION", "MASS_DATA_EXFIL"],
        "requires": [],
        "terminal": False,
        "severity": "HIGH",
        "mitre_stage": "DISCOVERY",
        "effort": 1,
        "label": "App Model Invariant Violation",
    },
}

_ARTIFACT_VERBS: Dict[str, str] = {
    "CODE_EXEC":           "achieves remote code execution",
    "CLOUD_CREDS":         "exfiltrates cloud IAM credentials",
    "ACCOUNT_TAKEOVER":    "achieves full account takeover",
    "ADMIN_SESSION":       "obtains administrator-level session",
    "DB_ACCESS":           "gains direct database read/write access",
    "SOURCE_CODE":         "recovers full application source code",
    "FILE_READ_ARBITRARY": "reads arbitrary files from the filesystem",
    "INTERNAL_NETWORK":    "pivots to internal network services",
    "MASS_DATA_EXFIL":     "exfiltrates bulk user data",
    "PERSISTENT_XSS":      "deploys persistent XSS across all user sessions",
    "SIGNING_KEY":         "recovers the application signing key",
    "PARTIAL_SOURCE":      "recovers partial application source",
    "CREDENTIALS":         "obtains valid credentials",
    "SSRF_PRIMITIVE":      "establishes a server-side request forgery primitive",
    "TEMPLATE_EXEC":       "achieves template engine execution",
    "DNS_CONTROL":         "gains DNS control over a subdomain",
    "STORED_PAYLOAD":      "stores a persistent injection payload",
}

__all__ = [
    "_FINDING_ARTIFACT_MAP",
    "_ARTIFACT_VERBS",
]
