"""Static scanner catalog data."""

from typing import Dict

from . import artifacts as _artifacts
from . import payloads as _payloads
from . import playbooks as _playbooks
from . import profiles as _profiles
from . import signatures as _signatures
from .artifacts import *
from .payloads import *
from .playbooks import *
from .profiles import *
from .signatures import *

_REMEDIATION: Dict[str, str] = {
    "xss":                        "Encode output; use Content-Security-Policy; avoid innerHTML",
    "xss filter bypass":          "Encode output; use strict CSP; avoid eval/innerHTML",
    "xss context-aware":          "Encode output in correct context (HTML/JS/attr); apply strict CSP",
    "dom xss sinks":              "Never pass user data to innerHTML/eval; use textContent",
    "sqli error":                 "Use parameterized queries / prepared statements",
    "sqli blind timing":          "Use parameterized queries; disable error messages",
    "nosql":                      "Validate and type-check all NoSQL operator inputs",
    "nosql blind oracle":         "Validate and type-check all NoSQL operator inputs",
    "ldap":                       "Escape LDAP special chars or use allowlist validation",
    "lfi":                        "Allowlist file paths; disable path traversal; chroot",
    "php wrapper lfi":            "Disable dangerous php:// wrappers; validate file params",
    "command injection":          "Never pass user data to shell; use execvp/subprocess arrays",
    "oob cmdi":                   "Never pass user data to shell; block outbound from app server",
    "ssti":                       "Use sandboxed template engines; never render user-controlled templates",
    "ssti engine fingerprint":    "Use sandboxed template engines; patch to latest version",
    "open redirect":              "Use allowlist for redirect targets; reject arbitrary URLs",
    "crlf injection":             "Strip \\r\\n from headers; use framework-level header encoding",
    "cors arbitrary origin":      "Set explicit allowed origins; never reflect Origin header",
    "cors misconfiguration":      "Set explicit allowed origins; remove wildcard with credentials",
    "cors private network":       "Add Access-Control-Allow-Private-Network only to trusted pages",
    "security headers":           "Add HSTS, X-Frame-Options, X-Content-Type-Options, CSP",
    "csp analysis":               "Tighten CSP: remove unsafe-inline, unsafe-eval, wildcards",
    "cookie flags":               "Add Secure, HttpOnly, SameSite=Strict to session cookies",
    "csrf form detection":        "Add CSRF tokens to all state-changing forms",
    "crawler + form fuzzer":      "Validate and sanitize all form inputs server-side; use parameterized queries; encode output; enforce Content-Security-Policy",
    "csrf poc generator":         "Add CSRF tokens; set SameSite=Strict on session cookies",
    "idor probe":                 "Enforce server-side authorization checks on every resource",
    "auth ip bypass headers":     "Remove trust of X-Forwarded-For for auth decisions",
    "jwt surface":                "Validate alg; reject 'none'; verify signature on every request",
    "jwt weak secret":            "Use long random secrets (256-bit+) for HMAC JWT signing",
    "jwt algorithm confusion":    "Pin accepted algorithm; reject 'none'; validate signature",
    "jwt kid injection":          "Sanitize kid header; do not use it in file paths or SQL",
    "sensitive paths":            "Remove or restrict access to sensitive files and endpoints",
    "backup extensions":          "Remove backup/temp files from web root; block .bak/.old/.swp",
    "directory listing":          "Disable directory indexing in web server config",
    "secret patterns in html":    "Move secrets to env vars; audit JS bundles for leakage",
    "html comment secrets":       "Strip HTML comments from production; audit templates",
    "js file secrets":            "Move API keys out of frontend JS; use backend proxy",
    "entropy analysis":           "Audit high-entropy strings; rotate any leaked credentials",
    "tls quality":                "Disable TLS 1.0/1.1; use strong cipher suites; renew certs",
    "http plaintext entry":       "Redirect HTTP to HTTPS; add HSTS preload",
    "mixed content":              "Serve all resources over HTTPS; fix HTTP asset URLs",
    "host header reflection":     "Validate Host header against allowlist; use SERVER_NAME",
    "cache host poisoning":       "Do not use unkeyed headers in cache keys or responses",
    "http verbs":                 "Disable TRACE; restrict PUT/DELETE to authenticated users",
    "xxe xml post":               "Disable external entity processing in XML parsers",
    "oob xxe":                    "Disable external entities and DTDs in XML parsers",
    "ssrf param echo":            "Validate and allowlist URLs; block internal IP ranges",
    "oob ssrf":                   "Validate and allowlist URLs; block SSRF via egress firewall",
    "cloud metadata ssrf":        "Block 169.254.169.254 at network layer; use IMDSv2",
    "path traversal url":         "Canonicalize paths; block ../ sequences; chroot",
    "graphql introspection":      "Disable introspection in production; add query depth limits",
    "graphql deep scan":          "Add query depth/complexity limits; disable introspection",
    "graphql field suggest":      "Disable field suggestions in production GraphQL",
    "http request smuggling":     "Normalize CL/TE headers; use HTTP/2 end-to-end",
    "rate limit detection":       "Implement rate limiting; add CAPTCHA on sensitive endpoints",
    "login brute-force protection": "Implement account lockout and rate limiting on login",
    "account enumeration":        "Return identical responses for valid/invalid usernames",
    "mass assignment":            "Explicitly allowlist accepted JSON fields; use DTOs",
    "deserialization surface":    "Avoid deserializing untrusted data; use allowlist types",
    "prototype pollution":        "Use Object.create(null); validate object merges",
    "file upload surface":        "Validate MIME type server-side; store outside web root",
    "source map exposure":        "Remove .js.map files from production deployments",
    "oauth oidc misconfiguration":"Validate redirect_uri strictly; use state parameter",
    "padding oracle":             "Use AEAD (GCM) instead of CBC; constant-time comparison",
    "log4shell jndi probe":       "Update log4j to 2.17.1+; set log4j2.formatMsgNoLookups",
    "oob log4shell":              "Update log4j to 2.17.1+; set log4j2.formatMsgNoLookups",
    "ssti oob":                   "Never render user-controlled data through a template engine; use static templates with escaped variable substitution only; sandbox or disable template execution at the framework level",
    "spring actuator exposed":    "Restrict actuator endpoints; require auth; remove /shutdown",
    "docker kubernetes exposure": "Remove Docker API from public network; use mTLS for k8s",
    "subdomain takeover":         "Remove dangling DNS records for decommissioned services",
    "nginx alias off-by-slash":   "Add trailing slash to all nginx alias directives",
    "h2c upgrade smuggling":      "Reject h2c Upgrade headers at load balancer",
    "cache key poisoning":        "Include security-sensitive headers in cache keys",
    "ssrf gopher/dict schemes":   "Allowlist URL schemes; reject gopher/dict/file",
    "esi injection":              "Disable ESI processing or sanitize user input in cached content",
    "xslt injection":             "Disable external XSLT loading; validate stylesheet sources",
    "dependency confusion":       "Claim internal package names in public registries",
    "xpath injection":            "Use parameterized XPath (XPath variables, not string concat)",
    "expression language injection": "Upgrade framework; disable EL evaluation on user input",
    "ssi injection":              "Disable SSI directives or sanitize user input in includes",
    "css injection":              "Encode CSS special chars; use CSP style-src nonce",
    "reflected file download":    "Validate Content-Disposition filename; do not reflect params",
    "null byte injection":        "Strip null bytes from input; validate file path params",
    "path parameter injection":   "Block semicolon path params; validate URL segments",
    "http method override":       "Ignore X-HTTP-Method-Override unless from trusted clients",
    "xssi json hijacking":        "Prefix JSON arrays with )]}'; set X-Content-Type-Options",
    "remote file inclusion":      "Disable allow_url_include; validate file/page params",
    "websocket hijacking":        "Validate Origin header on WebSocket handshake",
    "redos":                      "Audit regex patterns for catastrophic backtracking",
    "content-type confusion":     "Enforce strict Content-Type parsing; reject unexpected formats",
    "blind xss (oob)":            "Apply output encoding in ALL rendering contexts including admin/email; use CSP",
    "sqli union":                 "Use parameterized queries; principle of least privilege on DB user",
    "server timing leak":         "Remove Server-Timing and X-Runtime headers in production",
    "timing attack":              "Use constant-time comparison for secrets and credentials",
    "race condition":             "Use database transactions or distributed locks",
    "unicode encoding bypass":    "Normalize Unicode before validation; use NFC form",
    "postmessage/dom-clobbering audit": "Validate postMessage origin; avoid name-based DOM access",
    "csp bypass gadgets":         "Remove JSONP endpoints from CSP allowlist; use nonce-based CSP",
    "web cache deception":        "Use Cache-Control: no-store on private pages; validate extension",
    "dangling markup injection":  "Escape all user data in HTML; use strict CSP",
    "dns rebinding surface":      "Validate Host header strictly; do not trust client-supplied host",
    "js taint flow":              "Audit JS for location/event.data flows into innerHTML/eval",
    "breach compression oracle":  "Disable HTTP compression for sensitive dynamic pages",
    "token freshness oracle":     "Use CSPRNG for all tokens; rotate session tokens after auth; avoid timestamp-seeded tokens",
    "api version cliff":          "Enforce identical auth controls on all API versions; retire or firewall old versions",
    "response variance oracle":   "Standardize all LB nodes; strip internal IPs from responses; fix non-deterministic state",
    "polyglot file upload":       "Validate MIME server-side with libmagic; rename uploads; serve from content-delivery domain",
    "jwt audience confusion":     "Validate aud/iss claims on every endpoint; reject JWTs from foreign issuers; reject 'none' alg",
    "subdomain cookie scope":     "Set Domain to exact subdomain; add Secure+HttpOnly+SameSite=Strict to all session cookies",
    "MCP server unauthenticated":          "Add Bearer token or mTLS to all MCP endpoints; never expose agent protocol publicly",
    "MCP tool description poisoning":      "Sanitize all tool descriptions before passing to LLM; reject tools with instruction-override patterns",
    "MCP tool schema injection defaults":  "Audit input_schema defaults; escape all default parameter values; reject shell metacharacters",
    "MCP arbitrary file write":            "Remove file_write tools from production MCP servers; store uploads outside web root",
    "MCP SSRF via http_request tool":      "Block internal IP ranges in MCP HTTP client; allowlist permitted target domains",
    "MCP environment variable exfiltration": "Remove env inspection tools from production; never expose process environment via MCP",
    "MCP unauthenticated database access": "Remove database tools from production MCP servers; require explicit auth for all DB operations",
    "MCP CI/CD tool exposed":              "Require user confirmation + auth for all SCM/deploy tools; add approval workflow",
    "MCP filesystem roots exposed":        "Require auth on roots/list; restrict to minimal necessary paths",
    "MCP logging control unauthenticated": "Require auth on logging/setLevel; attacker can enable debug mode to capture secrets",
    "MCP completion oracle exposed":       "Require auth on completion/complete; prevents LLM knowledge probing",
    "MCP resource content read":           "Require auth on resources/read; restrict to non-sensitive URIs only",
    "MCP auto-remediation: endpoint still open": "Manually disable MCP server or add reverse proxy with Bearer token auth",
    "MCP dangerous tools exposed":"Remove dangerous tools (shell/file/exec) from production MCP servers; use allowlists",
    "MCP RCE via file read":      "Immediately restrict MCP server network access; require mTLS + authz on all tool calls",
    "MCP RCE via shell tool":     "Immediately restrict MCP server network access; remove all exec/shell tools from production",
    "MCP sampling API abuse":     "Require API key for sampling/createMessage; add rate limits and cost caps per identity",
    "MCP system prompts exposed": "Do not expose prompts/list unauthenticated; system prompts reveal agent capabilities",
    "MCP resources exposed":      "Require auth on resources/list; resource URIs may expose internal paths and data sources",
    "MCP/AI agent exposure":      "Remove or auth-gate plugin manifests and OpenAPI specs with agent annotations",
    "polyglot injection":         "Apply context-aware encoding for all injection categories",
    "second order injection":     "Treat stored data as untrusted when used in queries/commands",
    "parameter type confusion":   "Type-check all input parameters server-side",
    "php type juggling":          "Use strict comparison (===); avoid loose type coercions",
    "hidden parameter discovery": "Remove undocumented parameters; apply input validation",
    "business logic":             "Test negative/boundary values; enforce business rules server-side",
    "cve fingerprint":            "Patch identified frameworks and libraries to latest versions",
    "subdomain enumeration":      "Reduce exposed subdomains; restrict DNS zone transfers",
    "verb tunneling":             "Ignore X-HTTP-Method-Override in production",
    "external script sri":        "Add integrity= attribute to all external <script> tags",
    "clickjacking advanced":      "Set X-Frame-Options: DENY or CSP frame-ancestors 'none'",
    "stack and proxy headers":    "Strip internal headers (X-Powered-By, X-AspNet-Version)",
    "db admin files":             "Remove or restrict access to phpMyAdmin, adminer, etc.",
    "config yaml exposed":        "Block access to .yml/.yaml config files; move outside web root",
    "debug endpoints":            "Disable debug routes before deploying to production",
    "git head":                   "Block /.git/ access in web server config; remove .git from web root",
    "jwt kid injection":          "Sanitize kid header; never use it in file paths or SQL",
    "second order injection":     "Treat stored data as untrusted on retrieval",
    "js library cve":             "Upgrade flagged JS libraries to patched versions; pin via SRI hash",
    "client-side path traversal": "Validate user input before URL path concat; encodeURIComponent() and reject ../ ; use allowlist of API paths",
    "referrer policy":            "Set Referrer-Policy: strict-origin-when-cross-origin",
    "permissions policy":         "Set Permissions-Policy to restrict camera, microphone, geolocation, payment",
    "reporting headers":          "Review Report-To endpoints; ensure they are first-party or trusted",
    "cache control sensitive":    "Add Cache-Control: no-store to all sensitive/authenticated endpoints",
    "csp scheme wildcards":       "Remove data:/blob:/unsafe-hashes from script-src; use nonce-based CSP",
    "appcache manifest":          "Remove AppCache manifests; use Service Workers instead",
    "http2 rapid reset surface":  "Patch server: nginx>=1.25.3, Apache>=2.4.58; disable HTTP/2 if unpatched",
    "sri same origin libs":       "Add integrity= SRI hash to all same-origin vendor scripts",
    "duplicate setcookie":        "Eliminate duplicate Set-Cookie headers; ensure consistent security flags",
    "webauthn config":            "Restrict WebAuthn allowed origins to exact HTTPS origins only",
    "graphql alias dos":          "Implement GraphQL query complexity/alias limits; use query cost analysis",
    "jwks endpoint":              "Never expose private key components; use 2048-bit+ RSA keys; restrict JWKS access",
    "http3 downgrade":            "Audit HTTP/3 Alt-Svc max-age; ensure HTTP/3 only advertised over TLS",
    "cache poison xfh":           "Strip X-Forwarded-Host at load balancer; never reflect into cacheable responses",
    "oauth pkce enforcement":     "Enforce PKCE S256 for all public clients; reject plain method and missing code_challenge",
    "saml sigwrap surface":       "Require signed assertions; enable signature validation; patch XML signature wrapping",
    "redis unauth":               "Bind Redis to 127.0.0.1; add requirepass; use TLS; firewall port 6379",
    "elasticsearch unauth":       "Enable Elasticsearch security (xpack.security.enabled=true); add auth; firewall 9200",
    "mongodb unauth":             "Disable MongoDB REST interface; enable auth; bind to 127.0.0.1; firewall 27017/28017",
    "kubernetes etcd kubelet":    "Disable kubelet read-only port; enable etcd TLS+auth; firewall 2379/2380/6443/10255",
    "zd palo globalprotect":      "Upgrade PAN-OS to 11.1.2-h3 / 11.0.4-h1 / 10.2.9-h1+; see PSIRT advisory",
    "zd teamcity auth bypass":    "Upgrade TeamCity to 2023.11.4+; see CVE-2024-27198 JetBrains advisory",
    "zd ivanti connectsecure":    "Apply Ivanti patches for CVE-2023-46805/CVE-2024-21893; check CISA KEV",
    "zd moveit transfer":         "Upgrade MOVEit Transfer to 2023.0.1+; apply Progress advisory patches",
    "zd jenkins cli read":        "Upgrade Jenkins to 2.442+ / LTS 2.426.3+; see CVE-2024-23897 advisory",
    "zd php cgi argv":            "Upgrade PHP to 8.3.8+/8.2.20+/8.1.29+; disable CGI mode on Windows",
    "zd openssh regression":     "Upgrade OpenSSH to 9.8p1+; apply OS vendor patches for CVE-2024-6387",
    "zd confluence ssti":         "Upgrade Confluence to 8.5.4+/7.19.18+; see CVE-2023-22527 Atlassian advisory",
    "zd connectwise screenconnect": "Upgrade ScreenConnect to 23.9.8+; see CVE-2024-1709 ConnectWise advisory",
    "zd citrix bleed":            "Patch Citrix NetScaler to 13.1-49.13+ / 13.0-91.13+ / 12.1-55.18+; see CVE-2023-4966",
    "zd gitlab pwreset":          "Upgrade GitLab to 16.7.2+ / 16.6.4+ / 16.5.6+; see CVE-2023-7028 advisory",
    "zd apache activemq":         "Upgrade ActiveMQ to 5.15.16+ / 5.16.7+ / 5.17.6+ / 5.18.3+; see CVE-2023-46604",
    "zd checkpoint vpn":          "Apply Check Point hotfix for CVE-2024-24919; upgrade to R81.20 Take 45 / R81.10 Take 101+",
    "zd fortios auth bypass":     "Upgrade FortiOS to 7.0.17+ / 7.2.13+; see CVE-2024-55591 Fortinet PSIRT advisory",
    "zd crushftp ssti":           "Upgrade CrushFTP to v11.1.0+; see CVE-2024-4040 advisory",
    "zd sonicwall sma":           "Apply SonicWall SMA100 hotfix for CVE-2025-23006; see SonicWall PSIRT advisory",
    "zd f5 bigip icontrol":       "Upgrade BIG-IP to 16.1.2.2+ / 15.1.5.1+ / 14.1.4.6+ / 13.1.5+; block mgmt port; see CVE-2022-1388",
    "zd nextjs middleware bypass": "Upgrade Next.js to 15.2.3+ / 14.2.25+ / 13.5.9+ / 12.3.5+; see CVE-2025-29927 Vercel advisory",
    "zd fortimanager fortijump":  "Upgrade FortiManager to 7.6.1+ / 7.4.5+ / 7.2.8+ / 7.0.13+ / 6.4.15+; see CVE-2024-47575 Fortinet PSIRT advisory",
    "zd zimbra rce":              "Upgrade Zimbra to 10.0.9+ / 9.0.0 Patch 41+ / 8.8.15 Patch 46+; see CVE-2024-45519 advisory",
    "zd veeam backup rce":        "Upgrade Veeam Backup & Replication to v12.2 (build 12.2.0.334)+; see CVE-2024-40711 advisory",
    "zd tomcat partial put":      "Upgrade Apache Tomcat to 11.0.3+ / 10.1.35+ / 9.0.99+; see CVE-2025-24813 advisory",
    "zd ivanti cs stackoverflow": "Upgrade Ivanti Connect Secure to 22.7R2.6+; see CVE-2025-22457 Ivanti PSIRT advisory",
    "zd sap netweaver vc upload": "Apply SAP Security Note 3594142; disable Visual Composer if unused; see CVE-2025-31324 SAP advisory",
    "zd cisco iosxe webui":       "Disable IOS XE HTTP/HTTPS server if unused; patch to 17.3.8a+/17.6.6a+/17.9.4a+/17.10.1b+/17.11.1a+/17.15.2a+; see CVE-2023-20198/20273/CVE-2025-20188",
    "coop coep corp":                "Set Cross-Origin-Opener-Policy: same-origin; Cross-Origin-Embedder-Policy: require-corp; Cross-Origin-Resource-Policy: same-origin",
    "document policy":               "Set Document-Policy and Origin-Agent-Cluster: ?1 for cross-origin isolated contexts",
    "clear site data":               "Add Clear-Site-Data: \"cache\",\"cookies\",\"storage\" to all logout responses",
    "hsts preload readiness":        "Set HSTS: max-age=31536000; includeSubDomains; preload; then submit to hstspreload.org",
    "nextjs data exposure":          "Restrict /_next/data/ route access; remove source maps from production",
    "nuxt payload exposure":         "Strip sensitive data from server-side Nuxt payload; remove source maps from production",
    "manifest exposure":             "Block web root access to package.json, Gemfile, requirements.txt, go.mod via server config",
    "vcs metadata":                  "Block /.svn/ /.hg/ /.bzr/ /CVS/ in web server config; remove VCS dirs from deployment",
    "grpc reflection":               "Disable gRPC server reflection in production (reflection.Register should be dev-only)",
    "odata soap metadata":           "Restrict /$metadata and WSDL endpoints to authenticated requests",
    "oauth state param":             "Require state parameter on all OAuth authorize requests; validate on callback",
    "saml weak algorithm":           "Use SHA-256+ signing (xmldsig#rsa-sha256); enable WantAuthnRequestsSigned and WantAssertionsSigned",
    "wordpress surface":             "Disable XML-RPC; restrict /wp-json/users endpoint; remove backup config files; hide version",
    "laravel django debug":          "Set APP_DEBUG=false; restrict log file access; disable Ignition in production; set DEBUG=False",
    "llm endpoints":                 "Require API key authentication on all LLM endpoints; restrict to internal network",
    "hasura admin":                  "Set HASURA_GRAPHQL_ADMIN_SECRET; disable console in production; restrict /v1/metadata",
    "gcp metadata ssrf":             "Block outbound access to 169.254.169.254; use IMDSv2-equivalent; validate SSRF parameters",
    "azure oracle alibaba imds":     "Block 169.254.169.254 and 100.100.100.200 at network layer; use managed identity safely",
    "firebase open db":              "Set restrictive Firebase security rules; require authentication for all reads/writes",
    "k8s manifest exposure":         "Move manifests outside web root; never store secrets in YAML/Dockerfile; use Secrets Manager",
    "zd apache ofbiz screen render": "Upgrade Apache OFBiz to 18.12.15+; see CVE-2024-38856 Apache advisory",
    "zd veeam backup deser":         "Upgrade Veeam Backup & Replication to v12.2 (build 12.2.0.334)+; see CVE-2024-40711",
    "zd fortios fgfm fmtstring":     "Upgrade FortiOS to 7.4.3+/7.2.7+/7.0.14+/6.4.15+; see CVE-2024-23113 Fortinet PSIRT",
    "zd cups browsed":               "Restrict cups-browsed to localhost only; upgrade cups-browsed to 2.0.1+; see CVE-2024-47176",
    "zd spring path traversal":      "Upgrade Spring Framework to 5.3.41+/6.0.25+/6.1.14+; see CVE-2024-38819",
    "zd solarwinds servu":           "Upgrade Serv-U to 15.4.2 HF 2+; see CVE-2024-28995 SolarWinds advisory",
    "zd zimbra postjournal":         "Upgrade Zimbra to 10.0.9+/9.0.0 P41+/8.8.15 P46+; disable postjournal if unused",
    "zd servicenow jelly":           "Apply ServiceNow Washington DC Patch 2+/Vancouver Patch 8+; see CVE-2024-4879",
    "zd activemq cve 2026 34197":    "Upgrade Apache ActiveMQ to 6.1.5+; see CVE-2026-34197 Apache advisory",
    "zd sharepoint cve 2026 32201":  "Apply Microsoft SharePoint patch for CVE-2026-32201 spoofing vulnerability; update via Windows Update or MSRC advisory",
    "zd sharepoint toolpane chain":  "Apply all April 2026 Microsoft SharePoint security patches; see MSRC KEV batch advisory",
    "zd langflow cve 2026 33017":    "Upgrade Langflow to patched release; require authentication on all API endpoints; see CVE-2026-33017",
    "zd fortinet cve 2026 21643":    "Apply Fortinet patch for CVE-2026-21643; restrict management interface access; see PSIRT advisory",
    "zd citrix bleed 2 cve 2025 5777": "Patch Citrix NetScaler ADC/Gateway for CVE-2025-5777; apply vendor hotfix immediately",
    "zd oracle ebs cve 2025 61882":  "Apply Oracle EBS CPU patch for CVE-2025-61882; restrict /OA_HTML/ access; see Oracle advisory",
    "zd exchange cve 2023 21529":    "Apply Microsoft Exchange Server cumulative update for CVE-2023-21529; see MSRC advisory",
    "zd ingress nginx cve 2025 1974":  "Upgrade Kubernetes Ingress NGINX to 1.11.5+ or 1.12.1+; restrict admission webhook to internal cluster access; see CVE-2025-1974",
    "zd cisco smartlic cve 2024 20439": "Disable Cisco Smart Licensing Utility when not in use; apply Cisco advisory patch for CVE-2024-20439/20440; restrict CSLU to trusted networks",
    "zd dlink nas cve 2024 10914":   "D-Link DNS-320/320LW/325/340L are end-of-life with no patch; immediately isolate from public networks; replace with supported hardware",
    "zd apache httpd cve 2024 38475": "Upgrade Apache HTTP Server to 2.4.60+; review mod_rewrite rules for user-controlled path segments; see CVE-2024-38475 Apache advisory",
    "zd parquet cve 2025 30065":     "Upgrade Apache Parquet Java (parquet-avro) to 1.15.1+; validate all Parquet file inputs; see CVE-2025-30065 Apache advisory",
    "zd erlang otp ssh cve 2025 32433": "Upgrade Erlang/OTP to 27.3.3+/26.2.5.11+/25.3.2.21+; disable SSH daemon if unused; see CVE-2025-32433 Erlang advisory",
    "zd aviatrix controller cve 2024 50603": "Upgrade Aviatrix Controller to 7.2.4996+; restrict controller access to trusted networks; see CVE-2024-50603 advisory",
    "zd beyondtrust pra cve 2024 12356": "Apply BeyondTrust security advisory for CVE-2024-12356/12686; upgrade PRA/RS immediately; see KEV 2024-12-19",
    "zd gladinet centrestack cve 2025 30406": "Upgrade CentreStack to patched release; rotate machineKey in web.config; see CVE-2025-30406 Gladinet advisory",
    "zd commvault command center cve 2025 34028": "Upgrade Commvault Command Center beyond vulnerable 11.38.x releases; apply vendor security advisory for CVE-2025-34028",
    "zd cisco iosxe cli cve 2025 20198": "Apply Cisco PSIRT advisory for CVE-2025-20198; restrict privileged CLI access and upgrade affected IOS XE firmware",
    "zd sonicwall ssl vpn cve 2024 53704": "Upgrade SonicWall SMA100 firmware; apply PSIRT advisory for CVE-2024-53704; restrict management access; see KEV 2025-02-13",
    "zd juniper junos cve 2025 21589": "Upgrade Junos OS to 21.4R3-S10+/22.2R3-S6+/22.4R3-S6+/23.2R2-S4+; disable J-Web if unused; see CVE-2025-21589 Juniper advisory",
    "zd paloalto expedition cve 2024 9463": "Upgrade Palo Alto Expedition to 1.2.96+; never expose Expedition to internet; see CVE-2024-9463/9464/9465 advisory",
    "zd ivanti pulse cve 2025 0282":       "Upgrade Ivanti Pulse Connect Secure to 22.7R2.5+ / 9.1R18.9+; apply CISA KEV mitigation; see CVE-2025-0282 advisory",
    "zd simplehelp cve 2024 57727":        "Upgrade SimpleHelp to v5.5.8 / v5.4.10 / v5.3.9+; restrict /simplehelp/private/ at reverse proxy; see CVE-2024-57727 advisory",
    "zd nakivo cve 2024 48248":            "Upgrade NAKIVO Backup & Replication to 10.9.4+; restrict /c/router to trusted networks; see CVE-2024-48248 advisory",
    "zd kibana cve 2025 25012":            "Upgrade Kibana to 8.17.1+ or 7.17.27+; verify open-redirect protections; see CVE-2025-25012 Elastic advisory",
    "zd telerik report cve 2024 4358":     "Upgrade Telerik Report Server to 2024 Q2 (10.1.24.605)+; block /ReportServer/Users/Register at firewall; see CVE-2024-4358 advisory",
    "zd cacti cve 2024 29895":             "Upgrade Cacti to 1.2.27+; disable cmd_realtime.php if unused; restrict Cacti to trusted networks; see CVE-2024-29895 advisory",
    "zd cleo harmony cve 2024 50623":      "Apply Cleo Harmony/VLTrader hotfix 5.8.0.24; block /Harmony/upload at WAF; see CVE-2024-50623 CISA KEV advisory",
    "zd wazuh cve 2025 24016":             "Upgrade Wazuh to 4.9.1+; restrict Wazuh API port 55000 to trusted management networks; see CVE-2025-24016 advisory",
    "zd wordpress hunk companion cve 2024 9707": "Upgrade Hunk Companion plugin to 1.9.0+; or deactivate/remove plugin; restrict /wp-json/ to authenticated users where possible; see CVE-2024-9707",
    "zd trimble cityworks cve 2025 0994":  "Upgrade Trimble Cityworks to 15.8.9+ or 23.10+; apply CISA KEV patch; see CVE-2025-0994 advisory",
    "ai prompt injection":           "Implement LLM guardrails (output filters, input sanitization, system-prompt isolation); require API key auth; monitor for adversarial prompts",
    "llm context bleed":             "Isolate conversation context per user/session; never share vector stores across tenants; add output filter blocking canary/verbatim instruction replay",
    "LLM system prompt partially exposed": "Add output filter blocking verbatim instruction echo; use a generic model persona; monitor for prompt extraction patterns",
    "LLM tool-call injection":       "Validate tool-call generation server-side; user input must never directly control tool name/arguments; require explicit allowlist of triggerable tools",
    "LLM model identity disclosed":  "Use a consistent model persona; add output filter suppressing vendor/version disclosure",
    "LLM memorization leak":         "Add PII/secret filters on LLM output; never echo back sensitive patterns; implement differential privacy guardrails",
    "Indirect prompt injection via stored": "Sanitize all data sources before RAG ingestion; treat stored content as untrusted; add injection-detection layer in retrieval pipeline",
    "swagger ui xss":                "Upgrade Swagger UI to 3.38.0+; sanitize ?url= and ?configUrl= parameters; remove Swagger UI from production if not required",
    "graphql batch ratelimit bypass": "Implement per-query rate limiting and query cost analysis; disable batching or limit batch size; add query depth and complexity limits",
    "http desync te cl":             "Normalize CL/TE headers at front-end proxy; use HTTP/2 end-to-end; reject requests with both Transfer-Encoding and Content-Length",
    "prototype pollution server":    "Use Object.create(null) for merge targets; sanitize __proto__ and constructor keys from JSON input; upgrade vulnerable npm packages",
    "password reset poisoning":      "Build reset links from a configured APP_URL, never from the Host header; ignore X-Forwarded-Host for email link generation",
    "jsonp endpoints":               "Replace JSONP with CORS; if JSONP is required, validate the callback name against a strict allowlist and authenticate the endpoint",
    "default credentials":           "Change all default credentials at deploy time; enforce credential complexity; disable unused admin accounts and web UIs",
    "lfi log poisoning":             "Allowlist file paths; chroot app; sanitize User-Agent before writing to logs; disable PHP short tags; upgrade LFI to prevented status",
    "email header injection":        "Strip \\r and \\n from all values inserted into email headers; use a mail library that rejects multi-line header values; validate email addresses with a strict RFC 5321 regex",
    "xxe svg upload":                "Disable external entity processing before parsing any uploaded XML/SVG/DOCX/XLSX; use libxml2 with LIBXML_NOENT disabled; reject SVG or transcode to PNG server-side before storage",
    "websocket fuzz":                "Apply the same input validation and output encoding to WebSocket messages as to HTTP requests; authenticate the WS handshake; rate-limit messages per connection",
    "session fixation":              "Regenerate session ID (session_regenerate_id / req.session.regenerate) immediately on every successful authentication; invalidate the pre-login token",
    "blind sqli boolean":            "Use parameterized queries / prepared statements for all database interactions; never construct SQL from user-controlled values; enforce least-privilege DB accounts",
    "put file write":                "Disable WebDAV and HTTP PUT on web servers unless explicitly required; use a dedicated file-upload API with auth; store uploads outside the web root",
    "dns zone transfer":             "Restrict AXFR to specific secondary nameserver IPs in bind allow-transfer; use TSIG keys for zone transfer authentication; audit all authoritative NS configs",
    "html injection":                "HTML-encode all reflected/stored output with htmlspecialchars(ENT_QUOTES); apply Content-Security-Policy to limit allowed tags even without JS execution",
    "js endpoint extraction":        "Audit JS bundles for exposed API paths and hardcoded credentials; use environment variables for secrets",
    "openapi param fuzz":            "Validate and sanitize all parameters declared in OpenAPI spec; use parameterized queries",
    "behavioral oracle":             "Investigate all flagged hot parameters manually; review anomalous endpoints for access control, injection, and logic flaws",
    "behavioral auth boundary":      "Enforce server-side authorization checks on every endpoint; never rely solely on cookie presence for access control",
    "behavioral cache confusion":    "Add Vary headers for all user-differentiating request headers; ensure cache keys include security-relevant request properties",
    "chrono diff":                   "Investigate endpoints that changed auth boundaries between scans; review recently added or removed endpoints for access control regressions",
    "deploy freshness":              "Upgrade stale code subtrees (>12 months); audit Last-Modified dates; ensure regular patching cadence for all components",
    "schema fuzz":                   "Add strict server-side type validation for all JSON fields; reject unexpected types with 400; never coerce attacker-controlled types",
    "error linguistics":             "Suppress stack traces in production; return generic error messages; configure framework error handlers to return sanitized responses",
    "dead code paths":               "Remove or restrict dead routes; audit admin/debug-named paths; disable or delete unused endpoints in production deployments",
    "session identity drift":        "Regenerate session ID after login (fixation); use CSPRNG for token generation; scope cookies precisely; validate JWT claims on every request",
    "token flow graph":              "Ensure auth tokens are never sent to third-party origins; audit src/href/action attributes for external token-bearing requests",
    "waf bypass surface":            "Test WAF rules against identified bypass shapes; add defense-in-depth (input validation + WAF); review WAF gap patterns for your vendor",
    "self consistency":              "Enforce identical authorization logic across all equivalent access paths (GET, GET?id=, POST find); use a single auth middleware layer",
    "hidden param bayesian":         "Remove undocumented parameters from production; apply input validation and authorization checks to all accepted parameters",
    "stack coherence":               "Investigate conflicting stack signals indicating proxy deception; audit infrastructure for hidden components or misconfigured headers",
    "wasm analysis":                 "Never hardcode secrets in WASM data segments; strip WASM name sections in production builds (wasm-opt --strip-debug); audit all WASI imports; use runtime secret injection via env vars",
    "import map injection":          "Serve import maps from a static allowlist; never build importmap JSON from user input; use SRI on importmap script tags",
    "fetch metadata policy":         "Implement Sec-Fetch-Site enforcement in middleware; reject cross-site requests to sensitive paths with 403; see Fetch Metadata Resource Isolation Policy",
    "oauth implicit flow":           "Disable response_type=token (implicit grant); use Authorization Code + PKCE; never expose tokens in URL fragments",
    "iis short filename":            "Enable requestFiltering in IIS to block tilde URLs; set notListFiles=true; patch IIS or use URL Rewrite to reject *~1* patterns",
    "memcached exposure":            "Bind Memcached to 127.0.0.1; add SASL authentication; firewall port 11211; use TLS via stunnel for remote access",
    "webdav exposure":               "Disable WebDAV (mod_dav) unless required; restrict PROPFIND/PUT/DELETE to authenticated users; block WebDAV verbs at WAF",
    "php info exposure":             "Remove phpinfo() pages from production; restrict /server-status to localhost; disable mod_info in Apache config",
    "prometheus exposure":           "Require authentication on /metrics endpoints; restrict to internal network; remove sensitive label values; use Prometheus pushgateway with auth",
    "hashicorp exposure":            "Bind Vault/Consul/Nomad APIs to internal interfaces; require ACL tokens; firewall ports 8200/8500/4646; use TLS mutual auth",
    "http trailer injection":        "Validate and strip HTTP trailer headers at reverse proxy; use HTTP/2 end-to-end to eliminate chunked trailer handling",
    "ssrf url parser confusion":     "Use a URL allowlist post-parse with a single trusted parser; reject any URL whose parsed hostname differs from display; block all private IP ranges",
    "graphql subscriptions":         "Require authentication on WebSocket GraphQL endpoints; validate Origin on WS handshake; rate-limit subscription connections per user",
    "ftp anonymous":                 "Disable anonymous FTP access; use SFTP/FTPS instead; bind FTP to internal interfaces; enforce strong credentials",
    "crlf header smuggling":         "Normalize and strip \\r\\n from all values inserted into HTTP headers; use a response framework that escapes headers automatically",
    "cors wildcard credentialed":    "Never combine Access-Control-Allow-Origin: * with credentials; reject Origin: null; use an explicit allowlist of trusted origins",
    "race window amplified":         "Use database-level idempotency keys; apply distributed locks (Redis SET NX) for coupon/transfer endpoints; add per-user rate limiting",
    "nginx merge slashes":           "Set merge_slashes off in nginx for reverse-proxy locations; validate decoded path against allowlist before proxying; block // sequences at WAF",
    "sso cas exposure":              "Restrict CAS serviceValidate to trusted service URLs; use HTTPS for all ticket validation; enforce service allowlist in CAS config",
    "dom xss headless":              "Never pass user-controlled data to innerHTML/eval/document.write; use textContent; apply strict CSP",
    "baseline differential":         "Investigate all endpoints showing boolean-state response differentials; use parameterized queries and input validation",
    "shadow route probe":            "Validate that feature-flag, canary, and service-mesh headers cannot unlock hidden routes or degrade security controls; treat all routing headers as untrusted at the edge; enforce authorization independently of routing metadata",
    "email dns security":            "Add SPF TXT record with -all; configure DKIM signing; set DMARC p=reject; monitor with dmarcian or similar",
    "mfa bypass":                    "Enforce OTP single-use server-side; bind MFA step to session; block direct POST to post-auth URLs; rate-limit OTP attempts; invalidate backup codes after use",
    "captcha weakness":              "Add reCAPTCHA v3 or hCaptcha to all sensitive forms; validate CAPTCHA server-side; replace image-based CAPTCHA with modern invisible CAPTCHA",
    "password policy":               "Enforce minimum 12-char passwords with complexity; reject top-10k common passwords; enforce policy at registration AND reset endpoints",
    "deep git exposure":             "Block /.git/ entirely in web server config; scan repo history for secrets; rotate any found credentials; add .git to deployment exclusion rules",
    "smtp open relay":               "Require SMTP AUTH for relay; restrict relaying to authenticated users only; add SPF/DMARC to reject unauthenticated senders; disable open relay in MTA config",
    "dns caa record":                "Add CAA DNS records (e.g. 0 issue 'letsencrypt.org') to restrict which CAs may issue TLS certificates for this domain",
    "ct log enumeration":            "CT log exposure is passive; monitor crt.sh/Censys for unauthorized cert issuance; use CAA records to restrict issuance; review all discovered subdomains",
    "deserialization gadget chain":  "Upgrade affected libraries immediately; use allowlist-based deserializers; add RASP deserialization hooks; migrate to JSON or MessagePack",
    "content negotiation attack":    "Return consistent responses regardless of Accept header; strip internal/admin fields from all representations; apply auth checks uniformly across content types",
    "http2 continuation flood":      "Upgrade to nginx 1.25.3+, Apache 2.4.59+, Node.js 21.7.3+/20.11.1+/18.20.0+; apply CVE-2024-27316 patches; set HTTP/2 HEADERS_LIMIT in server config",
    "dependency version cve":        "Update vulnerable dependencies immediately; automate CVE scanning with Dependabot or Snyk in CI; pin versions with integrity hashes in lock files",
    "http semantic equivalence":     "Normalize paths at a single canonical layer before any security check; use the same URL parser in WAF and app; reject double slashes, dot-segments, and percent-encoded path separators at the edge",
    "parameter dependency graph":    "Remove undocumented feature-flag parameters from production; treat all accepted parameters as part of the attack surface; require auth checks independent of parameter presence",
    "multi-vector fusion":           "Treat multi-class injection sinks as critical regardless of individual severity; fix at the data-flow level: parameterize queries, encode output, and use allowlist validation at the single injection point to fix all vectors simultaneously",
    "timing covariance oracle":      "Isolate privileged and public endpoint backend resources into separate connection pools; apply per-endpoint rate limits to prevent cross-endpoint starvation; enforce constant-time response padding on auth-adjacent endpoints to eliminate cross-boundary timing side-channels",
    "jwt jku x5u injection":         "Never trust jku/x5u/x5c JWT header fields from client-supplied tokens; pin the JWKS URL server-side; reject any JWT whose header references an external URL; validate kid against an allowlist",
    "graphql introspection bypass":  "Disable introspection at the engine level for all HTTP methods and content-types; disable field name suggestions in production; enforce query depth/complexity limits regardless of introspection state",
    "account takeover chain":        "Invalidate all sessions on password change; use CSPRNG reset tokens with 128+ bit entropy and 15-minute TTL; validate Host header against an allowlist before embedding in reset emails; enforce per-email reset cooldown",
    "kill chain oracle":             "Apply defense-in-depth: validate Host header against allowlist; strip auth-bypass headers at ingress; use allowlists for URL params, file paths, and template input; enforce RBAC on every endpoint; use CSPRNG with >=128-bit entropy for all tokens; sandbox or disable template engines for user input; block SSRF via egress firewall + IMDSv2; use parameterized queries and CSP; conduct regular adversarial kill-chain simulation exercises",
    "broken function level auth":    "Enforce RBAC checks on every HTTP verb at the framework middleware level, not inside handler logic; deny non-GET verbs by default and explicitly allowlist permitted methods per endpoint; strip X-HTTP-Method-Override and similar tunneling headers at the reverse proxy; never rely on obscure URLs as an access control mechanism; run automated BFLA tests in CI with authenticated and unauthenticated sessions",
    "jsonrpc exposure":              "Disable system.listMethods, rpc.discover, and system.describe in production; require authentication on every RPC method; enforce per-method authorization checks; rate-limit batch/multicall requests; bind JSON-RPC listeners to localhost only and proxy through authenticated API gateway",
    "sse injection":                 "Sanitize all query parameters that flow into SSE data/event fields - strip CR/LF characters to prevent newline injection; gate SSE endpoints behind authentication; restrict Access-Control-Allow-Origin to trusted origins; avoid echoing user-controlled data directly into event-stream output",
    "graphql mutation abuse":        "Enforce authentication and per-mutation RBAC checks; disable mutation batching or rate-limit per-mutation in batches; require anti-CSRF tokens or SameSite=Strict cookies for mutation requests; restrict cross-origin mutation access; disable introspection in production to prevent mutation enumeration; apply query complexity and depth limits to all operations",
    "service worker surface":        "Restrict service worker scope to the smallest path possible; avoid third-party importScripts; keep service worker scripts on short cache lifetimes; do not cache authenticated pages, API responses, or opaque cross-origin responses; require explicit allowlists in fetch handlers",
    "client storage exposure":       "Do not store bearer tokens, refresh tokens, API keys, or passwords in localStorage/sessionStorage/IndexedDB; use HttpOnly Secure SameSite cookies for session secrets",
    "well-known trust files":        "Review .well-known trust files for overly broad app-link, asset-link, WebFinger, OIDC, and MTA-STS exposure; restrict associated apps/domains to expected production identities",
    "origin policy drift graph":     "Apply one consistent security-header and cache-control policy across equivalent routes and sensitive route classes; deny cacheability for auth-adjacent content; enforce CSP/COOP/Referrer-Policy centrally",
    "authorization graph topology": "Authorization is enforced inconsistently across the application's resource graph. Fix at the graph layer: every endpoint that exposes a nested resource path (/parent/{id}/child/{child_id}) MUST re-validate the caller's authorization against the child resource independently of the parent - never assume that access to the parent implies access to all children. Implement a single resource-ownership check function that is called for every resource, regardless of how it is reached. Audit all public-facing collection endpoints to ensure object-level access control (OLAC) is enforced uniformly across all IDs in the collection, not just the IDs the developer tested. Remove or authentication-gate any endpoint that embeds private resource IDs or data in its response, since attackers can use these references to construct indirect access chains.",
    "authorization invariant falsification": "Authorization is enforced inconsistently across equivalent request pairs. Fix at the policy decision point: implement a single centralized authorization function called from every handler, never per-handler ad-hoc checks. Validate object ownership server-side using session-derived identity, never client-supplied IDs. Add deny-by-default authorization tests for every endpoint covering the eight invariant classes (IDOR, tenant isolation, verb tampering, idempotence, capability revocation, field-level RBAC, direct-object-via-parent, API bypass).",
    "concurrent race window": "Race condition vulnerabilities allow multiple concurrent requests to bypass atomic enforcement of business rules. Fix: (1) use database-level atomic operations (SELECT ... FOR UPDATE, atomic compare-and-swap, or pessimistic locking) for any read-modify-write on limited resources; (2) enforce uniqueness constraints at the database layer with a unique index, not only in application logic; (3) use idempotency keys on payment, transfer, and debit endpoints so duplicate concurrent requests are deduplicated server-side; (4) implement optimistic locking (ETag/version column) on all resources subject to concurrent modification; (5) never split a 'check limit -> decrement' into two queries - use a single atomic UPDATE ... WHERE counter > 0 pattern; (6) for coupon/voucher redemption use a single atomic UPDATE with a conditional WHERE valid=1 AND used=0 rather than SELECT then UPDATE.",
    "graphql attack surface": "GraphQL exposes a broader attack surface than REST because a single endpoint processes all operations. Fix: (1) disable introspection in production so the full schema is not disclosed to unauthenticated clients; (2) implement per-operation rate limiting that counts aliases as individual operations - a query with 100 aliases for 'login' is 100 login attempts; (3) enforce query depth limits (typically <=10) and query complexity limits to prevent CPU/memory exhaustion from deeply nested queries; (4) reject JSON arrays (batch operations) unless intentionally enabled, or apply rate limits per operation in a batch; (5) disable field suggestion ('Did you mean X?') error messages in production to prevent schema recovery without introspection; (6) enforce object-level authorization on every resolver - GraphQL does not provide authorization automatically, every id: argument must be validated against the caller's permissions.",
    "xxe injection": "XML External Entity injection allows attackers to read arbitrary files, perform SSRF, and in some configurations achieve RCE via the XML parser. Fix: (1) configure the XML parser to disable DOCTYPE declarations and external entities entirely - in Java use DocumentBuilderFactory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING,true); in Python use defusedxml; in PHP use libxml_disable_entity_loader(true); (2) disable XInclude processing if not required; (3) use JSON instead of XML for API input where possible; (4) if XML must be accepted, validate it against a strict schema (XSD) before processing; (5) for file uploads that may contain XML (SVG, docx, xlsx), parse them in a sandboxed process with no network access; (6) do not use SOAP unless required by integration requirements, and configure SOAP parsers with the same entity-disabling settings.",
    "prototype pollution": "Server-side prototype pollution corrupts the global Object.prototype in Node.js, affecting every object in the process for all subsequent requests. Fix: (1) freeze Object.prototype at application startup: Object.freeze(Object.prototype); (2) use a JSON body parser that strips __proto__, constructor, and prototype keys - express body-parser does NOT do this by default; (3) use qs library >=6.10.3 which rejects __proto__ keys in query strings; (4) replace lodash.merge/assign with safe alternatives (lodash.mergewith with a custom deny-list, or structuredClone); (5) avoid using untrusted user input as property names in object assignments or merge operations; (6) add a global property check middleware that rejects requests containing __proto__, constructor.prototype, or Object.prototype keys in any input.",
    "ssti template injection": "Server-side template injection gives the attacker arbitrary code execution on the server. Fix: (1) never pass user-controlled input to template rendering functions - use template variables ({{ name }}) for data, never string concatenation; (2) use sandboxed template environments where available (Jinja2 SandboxedEnvironment, Twig sandbox policy); (3) adopt a strict allowlist of permitted template variables and functions; (4) if user-defined template syntax is a product requirement, use a logic-less template engine (Mustache, Handlebars) that does not support arbitrary expression evaluation; (5) HTML-encode all output that originates from user data; (6) apply a WAF rule that rejects requests containing template syntax patterns ({{, ${, <%, #{) in user-supplied fields that feed into template rendering.",
    "web cache poisoning": "Web cache poisoning allows an attacker to store a malicious response in the cache so all subsequent users receive it - one HTTP request produces persistent XSS, open redirect, or resource hijack for every visitor. Fix: (1) audit which request headers are forwarded to the origin but excluded from the cache key (X-Forwarded-Host, X-Host, X-Forwarded-Scheme, Accept-Language) and either add them to the cache key or strip them at the CDN/proxy; (2) do not use X-Forwarded-Host or similar headers to construct absolute URLs, link hrefs, or script src attributes - use the configured canonical domain; (3) set Cache-Control: no-store on all responses that are personalised or authentication-dependent; (4) use Vary: headers to include security-relevant inputs in the cache key; (5) configure the CDN to normalise or strip unrecognised request headers before they reach the origin; (6) test for web cache deception: ensure private endpoints respond with Cache-Control: no-store and that static-extension path suffixes (/account.css) still enforce authentication.",
    "h2 binary desync": "HTTP/2 binary frame-level attacks exploit the H2->H1 protocol downgrade that most reverse proxies perform. Fix: (1) deploy HTTP/2 end-to-end between proxy and backend, eliminating the H1 translation layer entirely; (2) configure the proxy to reject or strip forbidden H2 headers (transfer-encoding, connection) before forwarding; (3) validate all pseudo-header values (:path, :method, :authority) for embedded CRLF and reject with RST_STREAM(PROTOCOL_ERROR) if found; (4) ensure the proxy normalises the :authority pseudo-header and does not blindly forward it as the H1 Host header; (5) enforce HTTP/2 SETTINGS_MAX_HEADER_LIST_SIZE and SETTINGS_MAX_FRAME_SIZE to limit CONTINUATION-frame header-block attacks; (6) apply CVE-2023-44487 mitigations: rate-limit RST_STREAM per connection, upgrade h2 library to a patched version, and set GOAWAY after excess resets; (7) in WAF rules, inspect the full reassembled header block (HEADERS + all CONTINUATION frames) rather than only the initial HEADERS frame.",
    "http request smuggling": "HTTP request smuggling allows attackers to desynchronize a front-end/back-end HTTP pipeline, enabling auth bypass, request capture, XSS on any origin, and cache poisoning. Fix: (1) configure both the front-end proxy and backend server to use the same protocol (HTTP/2 end-to-end eliminates CL.TE/TE.CL ambiguity entirely); (2) if HTTP/1.1 is required, configure the front-end to normalize or reject ambiguous requests with both Content-Length and Transfer-Encoding headers; (3) disable HTTP/1.1 keep-alive on the front-end->backend link, or ensure the backend rejects conflicting transfer-encoding headers with a 400; (4) do not allow the Upgrade: h2c header to reach the backend unless the proxy validates the entire HTTP/2 framing; (5) set a strict request timeout on the backend so incomplete chunked bodies do not linger in connection buffers; (6) configure WAF/proxy to reject Transfer-Encoding headers with obfuscated values (xchunked, chunked\\x0b, duplicate TE headers).",
    "http request smuggling oracle": "HTTP request smuggling allows attackers to desynchronize a front-end/back-end HTTP pipeline. Fix: reject ambiguous Content-Length/Transfer-Encoding combinations, normalize transfer encodings at the edge, and prefer HTTP/2 end-to-end where possible.",
    "prototype pollution oracle": "Server-side prototype pollution can corrupt shared object prototypes. Fix: reject __proto__/constructor/prototype keys at all parsers, upgrade vulnerable merge/querystring libraries, avoid recursive merges of untrusted input, and freeze Object.prototype where compatible.",
    "zd wp automatic cve 2024 27956":       "Upgrade WP Automatic plugin to 3.92.1+; see CVE-2024-27956 CVSS 9.8 KEV advisory",
    "zd grafana legacy plugin traversal": "Upgrade Grafana and installed plugins; verify any plugin path traversal finding against current Grafana advisories",
    "zd really simple security cve 2024 10924": "Upgrade really-simple-ssl WordPress plugin to 9.1.2+; see CVE-2024-10924 CVSS 9.8 KEV advisory",
    "zd jenkins file read cve 2024 43044":  "Upgrade Jenkins to 2.470+/LTS 2.452.3+/2.462.2+; see CVE-2024-43044 CVSS 8.8 Jenkins security advisory",
    "zd whatsupgold sqli cve 2024 6670":    "Upgrade Progress WhatsUp Gold to 24.0.1+; see CVE-2024-6670/6671 CVSS 9.8 KEV advisory",
    "zd roundcube xss cve 2024 37383":      "Upgrade Roundcube Webmail to 1.5.7+/1.6.7+; see CVE-2024-37383 CVSS 6.1 KEV advisory",
    "zd edimax camera cve 2025 1316":       "No patch available for Edimax IC-7100; immediately isolate from public networks; replace device; see CVE-2025-1316 CVSS 9.8 KEV advisory",
    "zd laravel env manipulation cve 2024 52301": "Upgrade Laravel to 11.30.0+/10.48.22+/9.52.17+; see CVE-2024-52301 advisory",
    "zd sharepoint deser cve 2024 38094":   "Apply Microsoft SharePoint October 2024 Cumulative Update; see CVE-2024-38094 CVSS 7.2 KEV MSRC advisory",
    "zd cleo harmony cve 2024 55956":       "Apply Cleo Harmony/VLTrader hotfix 5.8.0.24+; block autorun directory at WAF; see CVE-2024-55956 CVSS 9.8 KEV Cleo advisory",
    "source code static scan":       "Remove hardcoded secrets, rotate any exposed credentials, and replace dangerous APIs with safe framework helpers",
    "sbom dependency scan":          "Pin dependency versions, review SBOM/manifests in CI, and verify high-profile packages against current advisories",
}

_SCAN_SEVERITY: Dict[str, str] = {
    "command injection":                  "CRIT",
    "xxe xml post":                       "CRIT",
    "sqli blind timing":                  "CRIT",
    "blind xss (oob)":                    "CRIT",
    "sqli union":                         "CRIT",
    "lfi":                                "HIGH",
    "xss":                                "HIGH",
    "xss filter bypass":                  "HIGH",
    "sqli error":                         "HIGH",
    "ssti":                               "HIGH",
    "open redirect":                      "HIGH",
    "auth ip bypass headers":             "HIGH",
    "cors arbitrary origin":              "HIGH",
    "ssrf param echo":                    "HIGH",
    "path traversal url":                 "HIGH",
    "git head":                           "HIGH",
    "db admin files":                     "HIGH",
    "config yaml exposed":                "HIGH",
    "http request smuggling":             "CRIT",
    "http request smuggling oracle":      "CRIT",
    "concurrent race window":             "CRIT",
    "session token oracle":               "CRIT",
    "linguistic attack surface":          "HIGH",
    "h2 binary desync":                   "CRIT",
    "ssti template injection":            "CRIT",
    "web cache poisoning":                "HIGH",
    "graphql attack surface":             "HIGH",
    "xxe injection":                      "CRIT",
    "prototype pollution":                "MED",
    "prototype pollution oracle":         "CRIT",
    "crlf injection":                     "MED",
    "nosql":                              "MED",
    "ldap":                               "MED",
    "graphql introspection":              "MED",
    "sensitive paths":                    "MED",
    "backup extensions":                  "MED",
    "secret patterns in html":            "MED",
    "jwt surface":                        "MED",
    "host header reflection":             "MED",
    "cache host poisoning":               "MED",
    "debug endpoints":                    "MED",
    "http plaintext entry":               "MED",
    "security headers":                   "LOW",
    "advanced browser isolation headers": "LOW",
    "cookie flags":                       "LOW",
    "cookie prefix policy":               "LOW",
    "http verbs":                         "LOW",
    "error disclosure":                   "LOW",
    "directory listing":                  "LOW",
    "openapi json":                       "LOW",
    "external script sri":                "LOW",
    "robots.txt":                         "INFO",
    "sitemap patterns":                   "INFO",
    "stack and proxy headers":            "INFO",
    "nginx status path":                  "INFO",
    "waf detection":                      "INFO",
    "technology fingerprint":             "INFO",
    "rate limit detection":               "INFO",
    "tls quality":                        "HIGH",
    "csp analysis":                       "MED",
    "csp bypass headless":                "MED",
    "dom xss sinks":                      "HIGH",
    "dom xss headless":                   "HIGH",
    "js file secrets":                    "HIGH",
    "csrf form detection":                "HIGH",
    "http parameter pollution":           "MED",
    "mixed content":                      "MED",
    "s3 bucket exposure":                 "HIGH",
    "html comment secrets":               "LOW",
    "idor probe":                         "HIGH",
    "security.txt":                       "INFO",
    "deserialization surface":            "HIGH",
    "login brute-force protection":       "HIGH",
    "file upload surface":                "MED",
    "subdomain takeover":                 "HIGH",
    "clickjacking advanced":              "MED",
    "clickjacking headless":              "MED",
    "cors misconfiguration":              "HIGH",
    "jwt algorithm confusion":            "CRIT",
    "jwt weak secret":                    "CRIT",
    "race condition":                     "HIGH",
    "mass assignment":                    "HIGH",
    "graphql deep scan":                  "HIGH",
    "source map exposure":                "HIGH",
    "oauth oidc misconfiguration":        "HIGH",
    "api versioning exposure":            "MED",
    "business logic":                     "HIGH",
    "entropy analysis":                   "MED",
    "timing attack":                      "HIGH",
    "docker kubernetes exposure":         "CRIT",
    "polyglot injection":                 "HIGH",
    "second order injection":             "HIGH",
    "websocket detection":                "INFO",
    "websocket headless":                 "INFO",
    "cache deception":                    "HIGH",
    "dangling markup":                    "MED",
    "dns rebinding surface":              "HIGH",
    "graphql batch dos":                  "MED",
    "parameter type confusion":           "MED",
    "web cache deception":                "HIGH",
    "log4shell jndi probe":               "CRIT",
    "spring actuator exposed":            "HIGH",
    "cloud metadata ssrf":                "CRIT",
    "nginx alias off-by-slash":           "HIGH",
    "verb tunneling":                     "MED",
    "php type juggling":                  "HIGH",
    "cve fingerprint":                    "HIGH",
    "subdomain enumeration":              "INFO",
    "h2c upgrade smuggling":              "HIGH",
    "cache key poisoning":                "HIGH",
    "ssrf gopher/dict schemes":           "CRIT",
    "php wrapper LFI":                    "CRIT",
    "esi injection":                      "HIGH",
    "xslt injection":                     "HIGH",
    "dependency confusion":               "HIGH",
    "graphql field suggest":              "MED",
    "padding oracle":                     "CRIT",
    "hidden parameter discovery":         "HIGH",
    "crawler + form fuzzer":              "HIGH",
    "BREACH compression oracle":          "CRIT",
    "postMessage/DOM-clobbering audit":   "HIGH",
    "oob ssrf":                           "CRIT",
    "oob xxe":                            "CRIT",
    "oob cmdi":                           "CRIT",
    "oob log4shell":                      "CRIT",
    "ssti oob":                           "CRIT",
    "xss context-aware":                  "HIGH",
    "js taint flow":                      "HIGH",
    "ssti engine fingerprint":            "CRIT",
    "csp bypass gadgets":                 "HIGH",
    "csrf poc generator":                 "HIGH",
    "jwt kid injection":                  "CRIT",
    "unicode encoding bypass":            "HIGH",
    "server timing leak":                 "MED",
    "nosql blind oracle":                 "HIGH",
    "xssi json hijacking":               "HIGH",
    "reflected file download":           "HIGH",
    "null byte injection":               "MED",
    "path parameter injection":          "MED",
    "http method override":              "HIGH",
    "xpath injection":                   "HIGH",
    "remote file inclusion":             "CRIT",
    "account enumeration":               "MED",
    "expression language injection":     "CRIT",
    "ssi injection":                     "HIGH",
    "css injection":                     "MED",
    "websocket hijacking":               "HIGH",
    "cors private network":              "MED",
    "redos":                             "MED",
    "content-type confusion":            "MED",
    "js library cve":                    "HIGH",
    "client-side path traversal":        "HIGH",
    "referrer policy":                   "LOW",
    "permissions policy":                "LOW",
    "reporting headers":                 "LOW",
    "cache control sensitive":           "LOW",
    "csp scheme wildcards":              "MED",
    "appcache manifest":                 "MED",
    "http2 rapid reset surface":         "MED",
    "sri same origin libs":              "MED",
    "duplicate setcookie":               "MED",
    "webauthn config":                   "MED",
    "graphql alias dos":                 "HIGH",
    "jwks endpoint":                     "HIGH",
    "http3 downgrade":                   "HIGH",
    "cache poison xfh":                  "HIGH",
    "oauth pkce enforcement":            "HIGH",
    "saml sigwrap surface":              "HIGH",
    "redis unauth":                      "CRIT",
    "elasticsearch unauth":              "CRIT",
    "mongodb unauth":                    "CRIT",
    "kubernetes etcd kubelet":           "CRIT",
    "zd palo globalprotect":             "ZERO",
    "zd teamcity auth bypass":           "ZERO",
    "zd ivanti connectsecure":           "ZERO",
    "zd moveit transfer":                "ZERO",
    "zd jenkins cli read":               "ZERO",
    "zd php cgi argv":                   "ZERO",
    "zd openssh regression":            "ZERO",
    "zd confluence ssti":                "ZERO",
    "zd connectwise screenconnect":      "ZERO",
    "zd citrix bleed":                   "ZERO",
    "zd gitlab pwreset":                 "ZERO",
    "zd apache activemq":                "ZERO",
    "zd checkpoint vpn":                 "ZERO",
    "zd fortios auth bypass":            "ZERO",
    "zd crushftp ssti":                  "ZERO",
    "zd sonicwall sma":                  "ZERO",
    "zd f5 bigip icontrol":              "ZERO",
    "coop coep corp":                    "LOW",
    "document policy":                   "LOW",
    "clear site data":                   "LOW",
    "hsts preload readiness":            "LOW",
    "nextjs data exposure":              "MED",
    "nuxt payload exposure":             "MED",
    "manifest exposure":                 "MED",
    "vcs metadata":                      "MED",
    "grpc reflection":                   "MED",
    "odata soap metadata":               "MED",
    "oauth state param":                 "HIGH",
    "saml weak algorithm":               "HIGH",
    "wordpress surface":                 "HIGH",
    "laravel django debug":              "HIGH",
    "llm endpoints":                     "HIGH",
    "hasura admin":                      "HIGH",
    "gcp metadata ssrf":                 "CRIT",
    "azure oracle alibaba imds":         "CRIT",
    "firebase open db":                  "CRIT",
    "k8s manifest exposure":             "CRIT",
    "zd apache ofbiz screen render":     "ZERO",
    "zd veeam backup deser":             "ZERO",
    "zd fortios fgfm fmtstring":         "ZERO",
    "zd cups browsed":                   "ZERO",
    "zd spring path traversal":          "ZERO",
    "zd solarwinds servu":               "ZERO",
    "zd zimbra postjournal":             "ZERO",
    "zd servicenow jelly":               "ZERO",
    "zd activemq cve 2026 34197":        "ZERO",
    "zd sharepoint cve 2026 32201":      "ZERO",
    "zd sharepoint toolpane chain":      "ZERO",
    "zd langflow cve 2026 33017":        "ZERO",
    "zd fortinet cve 2026 21643":        "ZERO",
    "zd citrix bleed 2 cve 2025 5777":   "ZERO",
    "zd oracle ebs cve 2025 61882":      "ZERO",
    "zd exchange cve 2023 21529":        "ZERO",
    "zd ingress nginx cve 2025 1974":    "ZERO",
    "zd cisco smartlic cve 2024 20439":  "ZERO",
    "zd dlink nas cve 2024 10914":       "ZERO",
    "zd apache httpd cve 2024 38475":    "ZERO",
    "zd parquet cve 2025 30065":         "ZERO",
    "js endpoint extraction":            "MED",
    "openapi param fuzz":                "HIGH",
    "behavioral oracle":                 "MED",
    "behavioral auth boundary":          "HIGH",
    "behavioral cache confusion":        "MED",
    "chrono diff":                       "MED",
    "deploy freshness":                  "LOW",
    "schema fuzz":                       "HIGH",
    "error linguistics":                 "MED",
    "dead code paths":                   "MED",
    "session identity drift":            "HIGH",
    "token flow graph":                  "HIGH",
    "waf bypass surface":                "MED",
    "self consistency":                  "HIGH",
    "hidden param bayesian":             "HIGH",
    "stack coherence":                   "MED",
    "shadow route probe":                "HIGH",
    "email dns security":                "MED",
    "mfa bypass":                        "HIGH",
    "captcha weakness":                  "MED",
    "password policy":                   "MED",
    "deep git exposure":                 "CRIT",
    "smtp open relay":                   "HIGH",
    "dns caa record":                    "LOW",
    "ct log enumeration":                "INFO",
    "deserialization gadget chain":      "CRIT",
    "content negotiation attack":        "MED",
    "http2 continuation flood":          "MED",
    "dependency version cve":            "HIGH",
    "http semantic equivalence":         "HIGH",
    "parameter dependency graph":        "HIGH",
    "multi-vector fusion":               "HIGH",
    "timing covariance oracle":          "HIGH",
    "jwt jku x5u injection":             "CRIT",
    "graphql introspection bypass":      "MED",
    "account takeover chain":            "HIGH",
    "kill chain oracle":                 "CRIT",
    "broken function level auth":        "CRIT",
    "jsonrpc exposure":                  "HIGH",
    "sse injection":                     "HIGH",
    "graphql mutation abuse":            "HIGH",
    "service worker surface":            "HIGH",
    "client storage exposure":           "HIGH",
    "well-known trust files":            "MED",
    "origin policy drift graph":         "HIGH",
    "authorization invariant falsification": "CRIT",
    "authorization graph topology":         "CRIT",
    "concurrent race window":               "CRIT",
    "source code static scan":              "HIGH",
    "sbom dependency scan":                 "MED",
}



























































REMEDIATION = _REMEDIATION
SCAN_SEVERITY = _SCAN_SEVERITY

__all__ = ["REMEDIATION", "SCAN_SEVERITY", "_REMEDIATION", "_SCAN_SEVERITY"]
__all__ += _artifacts.__all__
__all__ += _payloads.__all__
__all__ += _signatures.__all__
__all__ += _playbooks.__all__
__all__ += _profiles.__all__
