"""Playbooks data for Apex."""

from __future__ import annotations

from typing import Dict, Tuple

_PLAYBOOKS: Dict[Tuple[str, str], Dict] = {
    ("sqli error", "django"): {
        "root_cause": "Raw SQL queries or ORM raw() calls with unsanitized user input.",
        "fix_steps": ["Use Django ORM queryset methods instead of raw SQL", "If raw SQL is required, use parameterized queries with %s placeholders", "Enable Django DEBUG=False in production to suppress SQL error details"],
        "code": {"language": "python", "before": "User.objects.raw('SELECT * FROM users WHERE name=%s' % name)", "after": "User.objects.filter(name=name)"},
        "verify": ["Run DAST scan with SQLi payloads and confirm no SQL errors in response"],
        "refs": ["https://docs.djangoproject.com/en/stable/topics/security/#sql-injection-protection"],
    },
    ("sqli error", "rails"): {
        "root_cause": "String interpolation in ActiveRecord queries bypasses parameterization.",
        "fix_steps": ["Use ActiveRecord parameterized queries with ? or named placeholders", "Avoid string interpolation in where() clauses", "Enable query logging in development to audit all SQL"],
        "code": {"language": "ruby", "before": "User.where(\"name = '#{params[:name]}'\").first", "after": "User.where(name: params[:name]).first"},
        "verify": ["Confirm no SQL error messages in HTTP responses"],
        "refs": ["https://guides.rubyonrails.org/security.html#sql-injection"],
    },
    ("sqli error", "express"): {
        "root_cause": "Template literal or string concatenation in SQL queries with user input.",
        "fix_steps": ["Use parameterized queries with ? placeholders in mysql/pg drivers", "Use an ORM like Sequelize or Prisma which parameterizes by default", "Sanitize and validate all query parameters"],
        "code": {"language": "javascript", "before": "db.query(`SELECT * FROM users WHERE id = ${req.params.id}`)", "after": "db.query('SELECT * FROM users WHERE id = ?', [req.params.id])"},
        "verify": ["Test with SQLi payloads and confirm no database errors in response"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html"],
    },
    ("sqli error", "spring"): {
        "root_cause": "JdbcTemplate or JPQL with string concatenation instead of parameterized queries.",
        "fix_steps": ["Use JdbcTemplate with ? parameters or named parameters", "Use Spring Data JPA repository methods which are parameterized by default", "Use @Query with :param syntax for custom queries"],
        "code": {"language": "java", "before": "jdbcTemplate.query(\"SELECT * FROM users WHERE name='\" + name + \"'\")", "after": "jdbcTemplate.query(\"SELECT * FROM users WHERE name=?\", name)"},
        "verify": ["Verify no SQL exceptions leak to HTTP responses"],
        "refs": ["https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#jdbc-JdbcTemplate"],
    },
    ("sqli error", "php-laravel"): {
        "root_cause": "DB::select() with string concatenation or raw() without bindings.",
        "fix_steps": ["Use Eloquent ORM or Query Builder with parameter binding", "Use DB::select() with bindings array as second argument", "Enable query logging to audit all generated SQL"],
        "code": {"language": "php", "before": "DB::select('SELECT * FROM users WHERE name = ' . $name)", "after": "DB::select('SELECT * FROM users WHERE name = ?', [$name])"},
        "verify": ["Confirm no SQL error output in responses"],
        "refs": ["https://laravel.com/docs/queries#raw-expressions"],
    },
    ("sqli error", "generic"): {
        "root_cause": "User-supplied input concatenated directly into SQL query string.",
        "fix_steps": ["Replace all string-concatenated SQL with parameterized prepared statements", "Apply principle of least privilege to database user", "Disable detailed SQL error output in production"],
        "code": {"language": "sql", "before": "SELECT * FROM users WHERE id = '" + "user_input" + "'", "after": "SELECT * FROM users WHERE id = ? (with prepared statement)"},
        "verify": ["Test with ' OR 1=1-- and confirm no SQL errors or unexpected data returned"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html"],
    },
    ("xss", "django"): {
        "root_cause": "Use of mark_safe() or |safe template filter on user-supplied data, or inline JavaScript with unescaped variables.",
        "fix_steps": ["Remove mark_safe() calls on user-controlled data", "Use Django template auto-escaping (enabled by default)", "Apply Content-Security-Policy header to block inline scripts"],
        "code": {"language": "python", "before": "return mark_safe(user_input)", "after": "return user_input  # Django templates auto-escape"},
        "verify": ["Inject <script>alert(1)</script> and confirm it is HTML-encoded in output"],
        "refs": ["https://docs.djangoproject.com/en/stable/topics/security/#cross-site-scripting-xss-protection"],
    },
    ("xss", "rails"): {
        "root_cause": "html_safe or raw helper applied to user input bypasses Rails ERB auto-escaping.",
        "fix_steps": ["Never call .html_safe or raw on user-supplied strings", "Use Rails content_tag helpers for dynamic HTML generation", "Add Content-Security-Policy via secure_headers gem"],
        "code": {"language": "ruby", "before": "<%= raw params[:q] %>", "after": "<%= params[:q] %>"},
        "verify": ["Confirm <script> tags in input are HTML-encoded in output"],
        "refs": ["https://guides.rubyonrails.org/security.html#cross-site-scripting-xss"],
    },
    ("xss", "express"): {
        "root_cause": "res.send() or template rendering with unescaped user input, or innerHTML assignment in client-side code.",
        "fix_steps": ["Use Helmet.js to set security headers including CSP", "Use a template engine with auto-escaping (Handlebars, Pug)", "Avoid res.send(userInput) directly; always encode"],
        "code": {"language": "javascript", "before": "res.send('<div>' + req.query.q + '</div>')", "after": "res.send('<div>' + escapeHtml(req.query.q) + '</div>')"},
        "verify": ["Confirm XSS payloads are encoded in HTML output"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html"],
    },
    ("xss", "spring"): {
        "root_cause": "Model attributes rendered in JSP/Thymeleaf with th:utext or <%=expression%> instead of properly escaped output.",
        "fix_steps": ["Use th:text instead of th:utext in Thymeleaf templates", "Use c:out or fn:escapeXml in JSP", "Configure Spring Security default XSS headers"],
        "code": {"language": "java", "before": "<div th:utext=\"${userInput}\"></div>", "after": "<div th:text=\"${userInput}\"></div>"},
        "verify": ["Inject <img src=x onerror=alert(1)> and confirm HTML encoding in response"],
        "refs": ["https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#unescaped-text"],
    },
    ("xss", "php-laravel"): {
        "root_cause": "Use of {!! !!} Blade unescaped syntax or echo without htmlspecialchars on user input.",
        "fix_steps": ["Use {{ }} Blade syntax which auto-escapes", "Replace {!! !!} with {{ }} for user-controlled data", "Add X-XSS-Protection and CSP headers via middleware"],
        "code": {"language": "php", "before": "{!! $userInput !!}", "after": "{{ $userInput }}"},
        "verify": ["Confirm script tags are entity-encoded in Blade output"],
        "refs": ["https://laravel.com/docs/blade#displaying-data"],
    },
    ("xss", "generic"): {
        "root_cause": "User-supplied data reflected in HTML response without output encoding.",
        "fix_steps": ["HTML-encode all user input before inserting into HTML context", "Apply Content-Security-Policy to restrict inline script execution", "Use textContent instead of innerHTML in JavaScript"],
        "code": {"language": "html", "before": "<div id='out'></div><script>out.innerHTML=location.hash</script>", "after": "<div id='out'></div><script>out.textContent=location.hash</script>"},
        "verify": ["Inject <svg/onload=alert(1)> and confirm it does not execute"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html"],
    },
    ("lfi", "django"): {
        "root_cause": "File path parameter constructed from user input and passed to open() or FileResponse without validation.",
        "fix_steps": ["Validate file paths against an allowlist of permitted paths", "Use os.path.realpath() and verify the resolved path starts with the allowed base directory", "Never use user input directly in file path operations"],
        "code": {"language": "python", "before": "open(BASE + request.GET['file'])", "after": "safe = os.path.realpath(os.path.join(BASE, request.GET['file']))\nif not safe.startswith(BASE): raise PermissionError()"},
        "verify": ["Test with ../etc/passwd and confirm path traversal is blocked"],
        "refs": ["https://docs.python.org/3/library/os.path.html#os.path.realpath"],
    },
    ("lfi", "rails"): {
        "root_cause": "File serving endpoint that uses user-supplied filename without sanitization.",
        "fix_steps": ["Use send_file with basename only; never allow path separators in filename param", "Validate filename against an allowlist of permitted files", "Store user-downloadable files outside the application root"],
        "code": {"language": "ruby", "before": "send_file Rails.root.join('files', params[:name])", "after": "send_file Rails.root.join('files', File.basename(params[:name]))"},
        "verify": ["Request /../../../etc/passwd and confirm 400/403 response"],
        "refs": ["https://guides.rubyonrails.org/security.html#file-uploads"],
    },
    ("lfi", "express"): {
        "root_cause": "Static file serving or readFileSync with unsanitized user-supplied path.",
        "fix_steps": ["Use path.resolve() and verify result starts with allowed base directory", "Use express.static() which has built-in path traversal protection", "Block requests containing .. in path parameters"],
        "code": {"language": "javascript", "before": "fs.readFileSync('./files/' + req.params.name)", "after": "const p = path.resolve('./files', req.params.name);\nif (!p.startsWith(path.resolve('./files'))) return res.sendStatus(403);"},
        "verify": ["Test ../../etc/passwd traversal and confirm blocked"],
        "refs": ["https://nodejs.org/en/docs/guides/security-best-practices"],
    },
    ("lfi", "spring"): {
        "root_cause": "ClassPathResource or FileSystemResource constructed from user-supplied path parameter.",
        "fix_steps": ["Validate file names against an allowlist", "Use canonical path comparison to prevent traversal", "Use Spring's ResourceLoader with explicit path validation"],
        "code": {"language": "java", "before": "new FileSystemResource(\"/uploads/\" + filename)", "after": "Path p = Paths.get(\"/uploads\", filename).normalize();\nif (!p.startsWith(\"/uploads/\")) throw new SecurityException();"},
        "verify": ["Confirm ../etc/passwd returns 400 not file contents"],
        "refs": ["https://owasp.org/www-community/attacks/Path_Traversal"],
    },
    ("lfi", "php-laravel"): {
        "root_cause": "include/require with user-supplied path or Storage::get() without path validation.",
        "fix_steps": ["Never use include/require with user-supplied paths", "Use Laravel Storage facade with validated filename only", "Strip directory separators from user-supplied file parameters"],
        "code": {"language": "php", "before": "include($_GET['page'] . '.php')", "after": "$allowed = ['home', 'about', 'contact'];\nif (in_array($_GET['page'], $allowed)) include($_GET['page'] . '.php');"},
        "verify": ["Test with ../../etc/passwd and confirm path traversal blocked"],
        "refs": ["https://laravel.com/docs/filesystem"],
    },
    ("lfi", "generic"): {
        "root_cause": "File path constructed from user input without canonicalization or allowlist validation.",
        "fix_steps": ["Canonicalize paths and verify they stay within the intended base directory", "Use an allowlist of permitted files or directories", "Log and alert on path traversal attempts"],
        "code": {"language": "text", "before": "open(base_dir + user_input)", "after": "safe_path = realpath(base_dir + user_input); assert safe_path.startswith(base_dir)"},
        "verify": ["Confirm ../../etc/passwd returns error not file contents"],
        "refs": ["https://owasp.org/www-community/attacks/Path_Traversal"],
    },
    ("command injection", "django"): {
        "root_cause": "subprocess.call() or os.system() with shell=True and user-supplied arguments.",
        "fix_steps": ["Use subprocess with a list of arguments instead of shell=True", "Never pass user input to shell commands", "Use Python libraries instead of shelling out where possible"],
        "code": {"language": "python", "before": "subprocess.call('ping ' + host, shell=True)", "after": "subprocess.call(['ping', '-c', '1', host])"},
        "verify": ["Inject ; id and confirm command output does not appear in response"],
        "refs": ["https://docs.python.org/3/library/subprocess.html"],
    },
    ("command injection", "rails"): {
        "root_cause": "system(), exec(), or backtick operators with user-supplied input.",
        "fix_steps": ["Use Open3.capture2 with array arguments to avoid shell interpretation", "Validate and allowlist command arguments", "Use pure-Ruby libraries instead of shelling out"],
        "code": {"language": "ruby", "before": "system(\"convert #{params[:file]} output.png\")", "after": "Open3.capture2('convert', params[:file], 'output.png')"},
        "verify": ["Inject ; cat /etc/passwd and confirm not executed"],
        "refs": ["https://guides.rubyonrails.org/security.html"],
    },
    ("command injection", "express"): {
        "root_cause": "child_process.exec() with string template including user-supplied data.",
        "fix_steps": ["Use child_process.execFile() or spawn() with array arguments", "Validate all arguments against a strict allowlist", "Consider using native Node.js APIs instead of shell commands"],
        "code": {"language": "javascript", "before": "exec(`convert ${req.body.file} output.png`)", "after": "execFile('convert', [req.body.file, 'output.png'])"},
        "verify": ["Inject shell metacharacters and confirm they are not executed"],
        "refs": ["https://nodejs.org/api/child_process.html#child_processexecfilefile-args-options-callback"],
    },
    ("command injection", "spring"): {
        "root_cause": "Runtime.exec() with string concatenation or ProcessBuilder with user input.",
        "fix_steps": ["Use ProcessBuilder with a List<String> of arguments", "Validate all user-supplied command arguments", "Use Java libraries instead of spawning processes where possible"],
        "code": {"language": "java", "before": "Runtime.getRuntime().exec(\"ping \" + host)", "after": "new ProcessBuilder(\"ping\", \"-c\", \"1\", host).start()"},
        "verify": ["Inject & id and confirm command injection is blocked"],
        "refs": ["https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html"],
    },
    ("command injection", "php-laravel"): {
        "root_cause": "shell_exec(), exec(), or system() with user-supplied input.",
        "fix_steps": ["Use escapeshellarg() and escapeshellcmd() on all user inputs", "Prefer PHP native functions over shelling out", "Run the web application process with minimal OS permissions"],
        "code": {"language": "php", "before": "shell_exec('ping ' . $_GET['host'])", "after": "shell_exec('ping ' . escapeshellarg($_GET['host']))"},
        "verify": ["Inject ; id and confirm command is not executed"],
        "refs": ["https://www.php.net/manual/en/function.escapeshellarg.php"],
    },
    ("command injection", "generic"): {
        "root_cause": "User input passed to OS command execution without sanitization.",
        "fix_steps": ["Never pass user input to shell commands", "Use language-native APIs instead of shell execution", "Apply allowlist validation on any command arguments"],
        "code": {"language": "text", "before": "os.system('cmd ' + user_input)", "after": "subprocess(['cmd', user_input])  # no shell=True"},
        "verify": ["Inject ; id and confirm no command output in response"],
        "refs": ["https://owasp.org/www-community/attacks/Command_Injection"],
    },
    ("ssti", "django"): {
        "root_cause": "Django template rendered with user-controlled template string via Template(user_input).render().",
        "fix_steps": ["Never render user-supplied strings as Django templates", "Use a sandboxed template engine like Jinja2 with restricted globals", "Validate and sanitize all template inputs"],
        "code": {"language": "python", "before": "Template(request.GET['t']).render(context)", "after": "# Never render user input as a template"},
        "verify": ["Inject {{7*7}} and confirm 49 is not returned"],
        "refs": ["https://docs.djangoproject.com/en/stable/ref/templates/api/"],
    },
    ("ssti", "rails"): {
        "root_cause": "ERB.new(user_input).result() or render inline with user-supplied template string.",
        "fix_steps": ["Never render user-supplied strings as ERB templates", "Use Liquid or Mustache for user-facing template customization", "Sanitize all template-like inputs"],
        "code": {"language": "ruby", "before": "ERB.new(params[:template]).result(binding)", "after": "# Use Liquid gem with restricted tag set for user templates"},
        "verify": ["Inject <%= 7*7 %> and confirm 49 is not rendered"],
        "refs": ["https://github.com/Shopify/liquid"],
    },
    ("ssti", "express"): {
        "root_cause": "Template engine (Pug/Handlebars/EJS) render called with user-supplied template string.",
        "fix_steps": ["Never pass user input as the template string itself", "Use a sandboxed template engine for user-customizable templates", "Restrict template engine globals and helpers"],
        "code": {"language": "javascript", "before": "pug.render(req.body.template)", "after": "// Use Handlebars with no-prototype helpers for user templates"},
        "verify": ["Inject #{7*7} and confirm 49 is not rendered"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/Injection_Prevention_Cheat_Sheet.html"],
    },
    ("ssti", "spring"): {
        "root_cause": "FreeMarker or Thymeleaf template rendered from user-supplied template string.",
        "fix_steps": ["Never use user input as a FreeMarker/Thymeleaf template source", "Use Freemarker BeansWrapper with restricted class access", "Disable template execution for untrusted input"],
        "code": {"language": "java", "before": "new Template(\"t\", new StringReader(userInput), config).process(model, out)", "after": "// Load templates only from classpath, never from user input"},
        "verify": ["Inject ${7*7} and confirm 49 is not in response"],
        "refs": ["https://freemarker.apache.org/docs/pgui_misc_beanwrapper.html"],
    },
    ("ssti", "php-laravel"): {
        "root_cause": "Blade::compileString(user_input) or renderString with user-controlled template.",
        "fix_steps": ["Never call Blade::compileString with user input", "Use Twig with Sandbox extension for user-customizable templates", "Escape all user data before template rendering"],
        "code": {"language": "php", "before": "Blade::compileString($request->input('template'))", "after": "// Use Twig with SandboxExtension for user templates"},
        "verify": ["Inject {{7*7}} and confirm 49 is not rendered"],
        "refs": ["https://twig.symfony.com/doc/3.x/api.html#sandbox-extension"],
    },
    ("ssti", "generic"): {
        "root_cause": "User-supplied string rendered as a template expression by a server-side template engine.",
        "fix_steps": ["Never render user-supplied strings as templates", "Use sandboxed engines for user-customizable content", "Allowlist permitted template syntax if user templates are required"],
        "code": {"language": "text", "before": "engine.render(user_input)", "after": "# Load templates from trusted static files only"},
        "verify": ["Inject {{7*7}} and confirm 49 is not in response"],
        "refs": ["https://owasp.org/www-community/attacks/Server_Side_Template_Injection"],
    },
    ("xxe xml post", "django"): {
        "root_cause": "xml.etree.ElementTree or lxml parsing user-supplied XML without disabling external entities.",
        "fix_steps": ["Use defusedxml library instead of standard xml.etree", "Set resolve_entities=False in lxml XMLParser", "Validate and reject XML with DOCTYPE declarations"],
        "code": {"language": "python", "before": "import xml.etree.ElementTree as ET; ET.fromstring(user_xml)", "after": "import defusedxml.ElementTree as ET; ET.fromstring(user_xml)"},
        "verify": ["Submit XML with <!DOCTYPE> entity and confirm it is rejected"],
        "refs": ["https://pypi.org/project/defusedxml/"],
    },
    ("xxe xml post", "rails"): {
        "root_cause": "Nokogiri XML parsing without NONET and NOENT options.",
        "fix_steps": ["Use Nokogiri::XML(xml, nil, nil, Nokogiri::XML::ParseOptions::NONET | NOENT)", "Reject requests with DOCTYPE declarations in XML", "Keep Nokogiri updated to latest version"],
        "code": {"language": "ruby", "before": "Nokogiri::XML(user_xml)", "after": "Nokogiri::XML(user_xml, nil, nil, Nokogiri::XML::ParseOptions::NONET | Nokogiri::XML::ParseOptions::NOENT)"},
        "verify": ["Submit XXE payload and confirm external entity is not fetched"],
        "refs": ["https://nokogiri.org/tutorials/parsing_an_html_xml_document.html"],
    },
    ("xxe xml post", "express"): {
        "root_cause": "XML parsing library (xml2js, fast-xml-parser) without XXE protections.",
        "fix_steps": ["Use fast-xml-parser with processEntities: false", "Reject XML bodies containing DOCTYPE declarations", "Use JSON APIs where XML is not strictly required"],
        "code": {"language": "javascript", "before": "const result = parser.parse(xmlBody)", "after": "const parser = new XMLParser({ processEntities: false }); parser.parse(xmlBody)"},
        "verify": ["Submit <!DOCTYPE> XXE payload and confirm no external fetch"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html"],
    },
    ("xxe xml post", "spring"): {
        "root_cause": "JAXB or SAXParser without feature flags to disable external entities and DTD processing.",
        "fix_steps": ["Set XMLConstants.FEATURE_SECURE_PROCESSING on DocumentBuilderFactory", "Disable DOCTYPE declarations with setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true)", "Use Jackson for JSON APIs instead of XML where possible"],
        "code": {"language": "java", "before": "DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(input)", "after": "DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();\ndbf.setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true);\ndbf.newDocumentBuilder().parse(input)"},
        "verify": ["Confirm external entity fetch is blocked for XXE payloads"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html"],
    },
    ("xxe xml post", "php-laravel"): {
        "root_cause": "simplexml_load_string() or DOMDocument::loadXML() without LIBXML_NOENT disabled.",
        "fix_steps": ["Use LIBXML_NONET | LIBXML_DTDLOAD flags", "Call libxml_disable_entity_loader(true) before parsing", "Validate input is not XML if XML parsing is not required"],
        "code": {"language": "php", "before": "simplexml_load_string($userXml)", "after": "libxml_disable_entity_loader(true);\nsimplexml_load_string($userXml, 'SimpleXMLElement', LIBXML_NOENT)"},
        "verify": ["Submit XXE payload and confirm external entity is not processed"],
        "refs": ["https://www.php.net/manual/en/function.libxml-disable-entity-loader.php"],
    },
    ("xxe xml post", "generic"): {
        "root_cause": "XML parser processes external entity declarations in user-supplied XML.",
        "fix_steps": ["Disable external entity resolution in the XML parser configuration", "Reject XML inputs containing DOCTYPE declarations", "Use JSON instead of XML for user-facing APIs where possible"],
        "code": {"language": "xml", "before": "<?xml version=\"1.0\"?>\n<!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]>", "after": "# Configure parser to reject DOCTYPE declarations"},
        "verify": ["Submit XXE payload and confirm /etc/passwd is not returned"],
        "refs": ["https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing"],
    },
    ("open redirect", "django"): {
        "root_cause": "Redirect target taken from user-supplied next or redirect_to parameter without validation.",
        "fix_steps": ["Use django.utils.http.is_safe_url() (renamed url_has_allowed_host_and_scheme in Django 3.0+)", "Allowlist permitted redirect URLs or restrict to same-origin paths", "Log and monitor redirect parameter usage"],
        "code": {"language": "python", "before": "return redirect(request.GET.get('next', '/'))", "after": "from django.utils.http import url_has_allowed_host_and_scheme\nnext_url = request.GET.get('next', '/')\nif not url_has_allowed_host_and_scheme(next_url, allowed_hosts={request.get_host()}): next_url = '/'\nreturn redirect(next_url)"},
        "verify": ["Test redirect to https://evil.com and confirm redirect is blocked"],
        "refs": ["https://docs.djangoproject.com/en/stable/ref/utils/#django.utils.http.url_has_allowed_host_and_scheme"],
    },
    ("open redirect", "rails"): {
        "root_cause": "redirect_to with user-supplied URL parameter without host validation.",
        "fix_steps": ["Use redirect_to with only_path: true for same-origin redirects", "Validate redirect targets against an allowlist of permitted hosts", "Avoid redirect parameters altogether where possible"],
        "code": {"language": "ruby", "before": "redirect_to params[:return_to]", "after": "redirect_to(params[:return_to], only_path: true)"},
        "verify": ["Confirm redirect to external domain is rejected"],
        "refs": ["https://api.rubyonrails.org/classes/ActionController/Redirecting.html"],
    },
    ("open redirect", "express"): {
        "root_cause": "res.redirect() with user-supplied URL without host validation.",
        "fix_steps": ["Validate redirect targets against an allowlist of permitted URLs", "Use relative paths for same-site redirects", "Reject URLs starting with // or containing ://"],
        "code": {"language": "javascript", "before": "res.redirect(req.query.next)", "after": "const next = req.query.next;\nif (!next || next.startsWith('/') && !next.startsWith('//')) res.redirect(next); else res.redirect('/');"},
        "verify": ["Test redirect to //evil.com and confirm blocked"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html"],
    },
    ("open redirect", "spring"): {
        "root_cause": "Controller redirect with UriComponentsBuilder or ModelAndView using user-supplied URL.",
        "fix_steps": ["Validate redirect target host against allowed host allowlist", "Use relative paths for internal redirects", "Implement a redirect registry with server-side token mapping"],
        "code": {"language": "java", "before": "return \"redirect:\" + redirectUrl", "after": "if (!redirectUrl.startsWith(\"/\")) redirectUrl = \"/\";\nreturn \"redirect:\" + redirectUrl"},
        "verify": ["Inject external URL as redirect and confirm blocked"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html"],
    },
    ("open redirect", "php-laravel"): {
        "root_cause": "redirect() helper or header('Location: ') with user-supplied URL.",
        "fix_steps": ["Use Laravel's redirect()->to() with explicit path only", "Validate URL against allowlist before redirecting", "Use signed URLs for parameterized redirects"],
        "code": {"language": "php", "before": "return redirect($request->input('next'))", "after": "$next = $request->input('next', '/');\nif (!str_starts_with($next, '/') || str_starts_with($next, '//')) $next = '/';\nreturn redirect($next)"},
        "verify": ["Confirm redirect to https://evil.com is blocked"],
        "refs": ["https://laravel.com/docs/redirects"],
    },
    ("open redirect", "generic"): {
        "root_cause": "Application redirects to user-supplied URL without validating the redirect target.",
        "fix_steps": ["Validate redirect target is same-origin or in an allowlist", "Reject URLs containing :// or starting with //", "Use a server-side token map for parameterized redirects"],
        "code": {"language": "text", "before": "Location: <user_supplied_url>", "after": "# Validate host before issuing redirect"},
        "verify": ["Test redirect to https://attacker.com and confirm blocked"],
        "refs": ["https://owasp.org/www-community/attacks/Unvalidated_Redirects_and_Forwards_Cheat_Sheet"],
    },
    ("cors arbitrary origin", "django"): {
        "root_cause": "django-cors-headers configured with CORS_ALLOW_ALL_ORIGINS=True or reflecting Origin header without validation.",
        "fix_steps": ["Set CORS_ALLOW_ALL_ORIGINS = False", "Specify CORS_ALLOWED_ORIGINS with an explicit list", "Never use CORS_ORIGIN_REGEX_WHITELIST with .* pattern"],
        "code": {"language": "python", "before": "CORS_ALLOW_ALL_ORIGINS = True", "after": "CORS_ALLOWED_ORIGINS = ['https://trusted.example.com']"},
        "verify": ["Send request with Origin: https://evil.com and confirm not reflected"],
        "refs": ["https://pypi.org/project/django-cors-headers/"],
    },
    ("cors arbitrary origin", "rails"): {
        "root_cause": "rack-cors configured with origins('*') or reflecting arbitrary Origin headers.",
        "fix_steps": ["Replace origins('*') with explicit allowed origins list", "Set credentials: false when wildcards must be used", "Audit all rack-cors route configurations"],
        "code": {"language": "ruby", "before": "origins '*'", "after": "origins 'https://trusted.example.com'"},
        "verify": ["Confirm Origin: https://evil.com is not echoed in ACAO header"],
        "refs": ["https://github.com/cyu/rack-cors"],
    },
    ("cors arbitrary origin", "express"): {
        "root_cause": "cors() middleware with origin: true or origin: '*' with credentials enabled.",
        "fix_steps": ["Use cors({ origin: ['https://trusted.com'] })", "Never combine origin: true with credentials: true", "Implement origin validation function with explicit allowlist"],
        "code": {"language": "javascript", "before": "app.use(cors({ origin: true, credentials: true }))", "after": "app.use(cors({ origin: ['https://trusted.com'], credentials: true }))"},
        "verify": ["Send Origin: https://evil.com and confirm not in ACAO response header"],
        "refs": ["https://expressjs.com/en/resources/middleware/cors.html"],
    },
    ("cors arbitrary origin", "spring"): {
        "root_cause": "@CrossOrigin with allowedOrigins='*' or WebMvcConfigurer.addCorsMappings with all origins.",
        "fix_steps": ["Replace allowedOrigins(\"*\") with explicit domain list", "Use allowedOriginPatterns() for wildcard subdomain cases", "Enable credentials only for explicitly listed origins"],
        "code": {"language": "java", "before": "@CrossOrigin(origins = \"*\")", "after": "@CrossOrigin(origins = \"https://trusted.example.com\")"},
        "verify": ["Confirm wildcard CORS is removed for credentialed requests"],
        "refs": ["https://spring.io/guides/gs/rest-service-cors/"],
    },
    ("cors arbitrary origin", "php-laravel"): {
        "root_cause": "fruitcake/laravel-cors configured with allowed_origins = ['*'] or paths reflecting Origin header.",
        "fix_steps": ["Set allowed_origins to explicit list in cors.php config", "Disable supports_credentials when using wildcard origins", "Audit CORS config in config/cors.php"],
        "code": {"language": "php", "before": "'allowed_origins' => ['*']", "after": "'allowed_origins' => ['https://trusted.example.com']"},
        "verify": ["Confirm Origin: https://evil.com not reflected in production"],
        "refs": ["https://github.com/fruitcake/laravel-cors"],
    },
    ("cors arbitrary origin", "generic"): {
        "root_cause": "Server reflects any Origin header in Access-Control-Allow-Origin response header.",
        "fix_steps": ["Maintain an explicit allowlist of trusted origins", "Never reflect the Origin header verbatim", "Use a CORS library instead of manual header setting"],
        "code": {"language": "http", "before": "Access-Control-Allow-Origin: <reflected origin>", "after": "Access-Control-Allow-Origin: https://trusted.example.com"},
        "verify": ["Test with Origin: null and Origin: https://evil.com; confirm neither reflected"],
        "refs": ["https://portswigger.net/web-security/cors"],
    },
    ("csrf form detection", "django"): {
        "root_cause": "CSRF middleware disabled or {% csrf_token %} missing from POST forms.",
        "fix_steps": ["Ensure django.middleware.csrf.CsrfViewMiddleware is in MIDDLEWARE", "Add {% csrf_token %} to all POST forms", "Use @csrf_protect decorator on views that handle state changes"],
        "code": {"language": "html", "before": "<form method='post'><input type='submit'></form>", "after": "<form method='post'>{% csrf_token %}<input type='submit'></form>"},
        "verify": ["Submit form without CSRF token and confirm 403 response"],
        "refs": ["https://docs.djangoproject.com/en/stable/ref/csrf/"],
    },
    ("csrf form detection", "rails"): {
        "root_cause": "protect_from_forgery disabled or :exception not raised for CSRF violations.",
        "fix_steps": ["Ensure protect_from_forgery with: :exception is in ApplicationController", "Do not use skip_before_action :verify_authenticity_token globally", "Use Rails UJS or Turbo which automatically include CSRF token"],
        "code": {"language": "ruby", "before": "protect_from_forgery with: :null_session", "after": "protect_from_forgery with: :exception"},
        "verify": ["POST without csrf token and confirm 422 response"],
        "refs": ["https://guides.rubyonrails.org/security.html#csrf-countermeasures"],
    },
    ("csrf form detection", "express"): {
        "root_cause": "No CSRF protection middleware on state-changing POST/PUT/DELETE routes.",
        "fix_steps": ["Use csrf npm package or csurf middleware on all state-changing routes", "Verify CSRF token on server side for every non-idempotent request", "Set SameSite=Strict on session cookies as defense-in-depth"],
        "code": {"language": "javascript", "before": "app.post('/transfer', handler)", "after": "const csrf = require('csurf')();\napp.post('/transfer', csrf, handler)"},
        "verify": ["POST without _csrf token and confirm 403"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html"],
    },
    ("csrf form detection", "spring"): {
        "root_cause": "Spring Security CSRF protection disabled via .csrf().disable().",
        "fix_steps": ["Remove .csrf().disable() from Spring Security config", "Use the default Spring Security CSRF token validator", "Include _csrf hidden field or X-CSRF-TOKEN header in forms"],
        "code": {"language": "java", "before": "http.csrf().disable()", "after": "// Remove csrf().disable() to enable Spring Security CSRF protection"},
        "verify": ["POST without CSRF token and confirm 403"],
        "refs": ["https://docs.spring.io/spring-security/site/docs/current/reference/html5/#csrf"],
    },
    ("csrf form detection", "php-laravel"): {
        "root_cause": "VerifyCsrfToken middleware disabled or route excluded from CSRF verification.",
        "fix_steps": ["Keep App\\Http\\Middleware\\VerifyCsrfToken in the middleware stack", "Remove routes from the $except array in VerifyCsrfToken", "Use @csrf Blade directive in all POST forms"],
        "code": {"language": "php", "before": "<form method='POST'><!-- no @csrf --></form>", "after": "<form method='POST'>@csrf</form>"},
        "verify": ["POST without _token and confirm 419 response"],
        "refs": ["https://laravel.com/docs/csrf"],
    },
    ("csrf form detection", "generic"): {
        "root_cause": "State-changing forms lack CSRF token protection.",
        "fix_steps": ["Add CSRF token to all state-changing forms", "Validate token server-side on every POST/PUT/DELETE", "Set SameSite=Strict on session cookies"],
        "code": {"language": "html", "before": "<form method='post'><!-- no token --></form>", "after": "<form method='post'><input type='hidden' name='csrf_token' value='SERVER_GENERATED_TOKEN'></form>"},
        "verify": ["POST without token and confirm rejected"],
        "refs": ["https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html"],
    },
    ("jwt weak secret", "django"): {
        "root_cause": "Django JWT secret (SECRET_KEY or JWT_SECRET_KEY) is short, default, or predictable.",
        "fix_steps": ["Generate SECRET_KEY with at least 50 random characters using secrets.token_hex(32)", "Rotate the key and invalidate all existing sessions", "Store key in environment variable, not in settings.py"],
        "code": {"language": "python", "before": "SECRET_KEY = 'django-insecure-key'", "after": "import secrets; SECRET_KEY = secrets.token_hex(50)  # store in env var"},
        "verify": ["Run offline JWT crack against captured tokens and confirm no match"],
        "refs": ["https://docs.djangoproject.com/en/stable/ref/settings/#secret-key"],
    },
    ("jwt weak secret", "rails"): {
        "root_cause": "JWT HMAC secret in Rails is short, in source control, or uses Rails.application.secret_key_base directly without rotation.",
        "fix_steps": ["Use Rails credentials for JWT secret with rails credentials:edit", "Ensure secret is at least 256 bits (32 bytes)", "Rotate secret and invalidate existing JWTs on suspicion of compromise"],
        "code": {"language": "ruby", "before": "JWT.encode(payload, 'secret', 'HS256')", "after": "JWT.encode(payload, Rails.application.credentials.jwt_secret!, 'HS256')"},
        "verify": ["Attempt offline brute-force of captured JWT and confirm secret not found"],
        "refs": ["https://github.com/jwt/ruby-jwt"],
    },
    ("jwt weak secret", "express"): {
        "root_cause": "jsonwebtoken secret is a short string, default value, or stored in source code.",
        "fix_steps": ["Generate secret with crypto.randomBytes(64).toString('hex')", "Store JWT secret in environment variable process.env.JWT_SECRET", "Consider using RS256 with asymmetric keys instead of HS256"],
        "code": {"language": "javascript", "before": "jwt.sign(payload, 'mysecret')", "after": "jwt.sign(payload, process.env.JWT_SECRET, { algorithm: 'HS256' })"},
        "verify": ["Confirm captured JWT cannot be cracked offline"],
        "refs": ["https://github.com/auth0/node-jsonwebtoken"],
    },
    ("jwt weak secret", "spring"): {
        "root_cause": "JWT signing secret in Spring Security is hardcoded or derived from a weak property.",
        "fix_steps": ["Use a minimum 256-bit key for HS256 via Keys.secretKeyFor(SignatureAlgorithm.HS256)", "Store secret in Spring Vault or environment variable", "Consider switching to RS256/ES256 with key pairs"],
        "code": {"language": "java", "before": "Keys.hmacShaKeyFor(\"secret\".getBytes())", "after": "Keys.secretKeyFor(SignatureAlgorithm.HS256)"},
        "verify": ["Verify JWT secret is not in source code or config files"],
        "refs": ["https://github.com/jwtk/jjwt"],
    },
    ("jwt weak secret", "php-laravel"): {
        "root_cause": "JWT_SECRET in .env is short, default, or the same as APP_KEY.",
        "fix_steps": ["Set JWT_SECRET to php artisan jwt:secret output (256-bit random)", "Store in .env file only, never commit to source control", "Rotate secret and call auth()->invalidate() on compromise"],
        "code": {"language": "php", "before": "JWT_SECRET=changeme", "after": "# Run: php artisan jwt:secret"},
        "verify": ["Confirm JWT secret is not guessable from captured tokens"],
        "refs": ["https://jwt-auth.readthedocs.io/en/develop/configuration/"],
    },
    ("jwt weak secret", "generic"): {
        "root_cause": "HMAC JWT signing secret is too short, predictable, or stored insecurely.",
        "fix_steps": ["Use a minimum 256-bit (32-byte) cryptographically random secret", "Rotate the secret immediately and invalidate all existing tokens", "Consider asymmetric RS256/ES256 to eliminate secret distribution risk"],
        "code": {"language": "text", "before": "jwt.sign(payload, 'password123')", "after": "jwt.sign(payload, cryptographically_random_256_bit_key)"},
        "verify": ["Run hashcat/john offline attack against captured token and confirm failure"],
        "refs": ["https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-best-practices"],
    },
    ("zd activemq cve 2026 34197", "generic"): {
        "root_cause": "Apache ActiveMQ improper input validation in OpenWire protocol allows code injection.",
        "fix_steps": ["Upgrade Apache ActiveMQ to version 6.1.5 or later", "Restrict access to ActiveMQ admin interface and OpenWire port 61616 to trusted networks only", "Monitor for exploitation indicators in ActiveMQ logs"],
        "code": {"language": "text", "before": "ActiveMQ < 6.1.5 exposed on network", "after": "ActiveMQ 6.1.5+ with port 61616 firewalled"},
        "verify": ["Confirm version upgrade and network access controls applied"],
        "refs": ["https://activemq.apache.org/security-advisories"],
    },
    ("zd sharepoint cve 2026 32201", "generic"): {
        "root_cause": "Microsoft SharePoint Server improper input validation allowing spoofing attacks.",
        "fix_steps": ["Apply Microsoft Security Update for CVE-2026-32201 via Windows Update or WSUS", "Apply to all SharePoint Server 2016, 2019, and Subscription Edition instances", "Monitor MSRC advisory for additional mitigations"],
        "code": {"language": "text", "before": "SharePoint unpatched", "after": "Apply CVE-2026-32201 security update"},
        "verify": ["Confirm patch installation via SharePoint Central Administration version check"],
        "refs": ["https://msrc.microsoft.com/"],
    },
    ("zd langflow cve 2026 33017", "generic"): {
        "root_cause": "Langflow unauthenticated public flow execution endpoint allows arbitrary code injection.",
        "fix_steps": ["Upgrade Langflow to the patched version", "Require authentication on all /api/v1/ endpoints", "Do not expose Langflow directly to the internet without authentication"],
        "code": {"language": "text", "before": "/api/v1/flows/ accessible without auth", "after": "Require API key or session auth on all Langflow API endpoints"},
        "verify": ["Confirm /api/v1/flows/ returns 401 without valid credentials"],
        "refs": ["https://github.com/langflow-ai/langflow/security"],
    },
    ("zd exchange cve 2023 21529", "generic"): {
        "root_cause": "Microsoft Exchange Server deserialization vulnerability newly added to CISA KEV.",
        "fix_steps": ["Apply Microsoft Exchange Server cumulative update containing CVE-2023-21529 fix", "Apply the latest Exchange Server Security Update", "Restrict /owa/ and /ecp/ access to internal networks where possible"],
        "code": {"language": "text", "before": "Exchange Server unpatched for CVE-2023-21529", "after": "Apply Exchange Server security update for CVE-2023-21529"},
        "verify": ["Confirm Exchange version shows patched CU via EAC version page"],
        "refs": ["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-21529"],
    },
}

__all__ = [
    "_PLAYBOOKS",
]
