"""Profiles data for Apex."""

from __future__ import annotations

from typing import Dict, List, Set, Tuple

_SLOW_SCANS: Set[str] = {
    "sqli blind timing", "oob ssrf", "oob xxe", "oob cmdi", "oob log4shell",
    "blind xss (oob)", "subdomain enumeration", "race condition",
    "nosql blind oracle", "padding oracle", "hidden parameter discovery",
    "rate limit detection", "crawler + form fuzzer",
    "application model synthesis", "hidden param bayesian",
    "js taint flow", "oracle synthesis",
    "causal security proof synthesis",
    "authorization invariant falsification",
    "authorization graph topology",
    "concurrent race window",
    "http request smuggling",
    "h2 binary desync",
    "ssti template injection",
    "web cache poisoning",
    "graphql attack surface",
    "xxe injection",
    "prototype pollution",
}

_FAST_MODULES: frozenset = frozenset({
    "waf detection",
    "technology fingerprint",
    "tls quality",
    "security headers",
    "csp analysis",
    "advanced browser isolation headers",
    "clickjacking advanced",
    "http verbs",
    "cookie flags",
    "cookie prefix policy",
    "http plaintext entry",
    "mixed content",
    "error disclosure",
    "secret patterns in html",
    "html comment secrets",
    "jwt surface",
    "robots.txt",
    "sitemap patterns",
    "security.txt",
    "sensitive paths",
    "host header reflection",
    "cors arbitrary origin",
    "cors misconfiguration",
    "cache host poisoning",
    "graphql introspection",
    "dom xss sinks",
    "js file secrets",
    "client storage exposure",
    "csrf form detection",
    "git head",
    "db admin files",
    "config yaml exposed",
    "debug endpoints",
    "source map exposure",
    "oauth oidc misconfiguration",
    "session fixation",
    "account enumeration",
    "spring actuator exposed",
    "cors private network",
    "swagger ui xss",
    "well-known trust files",
    "origin policy drift graph",
    "deception detection",
    "response consistency",
})

_FUSION_RULES: List[Tuple] = [
    ({"sqli error", "sqli blind timing", "error disclosure"}, "confirmed SQL injection sink", 2, "HIGH"),
    ({"sqli error", "sqli blind timing"}, "SQL injection via timing channel confirmed", 2, "HIGH"),
    ({"ssti", "error disclosure", "parameter type confusion"}, "template engine reachable via param", 2, "HIGH"),
    ({"ssti engine fingerprint", "error disclosure"}, "SSTI with confirmed engine type", 2, "HIGH"),
    ({"ssti", "ssti engine fingerprint"}, "SSTI engine fully confirmed", 2, "CRIT"),
    ({"open redirect", "oauth state param", "xss"}, "oauth takeover chain focal point", 2, "CRIT"),
    ({"open redirect", "oauth state param"}, "oauth CSRF token theft via redirect", 2, "HIGH"),
    ({"ssrf param echo", "timing attack"}, "SSRF to live internal service", 2, "HIGH"),
    ({"ssrf param echo", "server timing leak"}, "SSRF with internal timing oracle", 2, "HIGH"),
    ({"ssrf param echo", "error disclosure"}, "SSRF with verbose error disclosure", 2, "HIGH"),
    ({"command injection", "error disclosure"}, "command injection with verbose errors confirmed", 2, "CRIT"),
    ({"command injection", "parameter type confusion"}, "command injection via type confusion", 2, "CRIT"),
    ({"lfi", "error disclosure"}, "LFI path confirmed via error messages", 2, "HIGH"),
    ({"lfi", "parameter type confusion"}, "LFI via type confusion bypass", 2, "HIGH"),
    ({"xss", "error disclosure"}, "XSS with error-context injection point", 2, "HIGH"),
    ({"xss", "parameter type confusion"}, "XSS via type confusion route", 2, "HIGH"),
    ({"xss", "cors arbitrary origin"}, "XSS amplified by CORS origin reflection", 2, "HIGH"),
    ({"xss", "csrf form detection"}, "XSS enables CSRF token theft", 2, "HIGH"),
    ({"sqli error", "error disclosure"}, "SQL injection with verbose error disclosure", 2, "HIGH"),
    ({"nosql", "parameter type confusion"}, "NoSQL injection via type confusion", 2, "HIGH"),
    ({"nosql blind oracle", "timing attack"}, "NoSQL blind injection confirmed via timing", 2, "HIGH"),
    ({"path traversal url", "error disclosure"}, "path traversal confirmed via error messages", 2, "HIGH"),
    ({"path traversal url", "parameter type confusion"}, "path traversal via param type bypass", 2, "HIGH"),
    ({"jwt surface", "error disclosure"}, "JWT manipulation with verbose error info", 2, "MED"),
    ({"jwt weak secret", "parameter type confusion"}, "JWT with exploitable type confusion", 2, "HIGH"),
    ({"cors arbitrary origin", "cookie flags"}, "CORS with insecure cookies enables session theft", 2, "HIGH"),
    ({"open redirect", "error disclosure"}, "open redirect with verbose error confirmation", 2, "MED"),
    ({"ssti", "server timing leak"}, "SSTI with internal timing side-channel", 2, "CRIT"),
    ({"lfi", "ssrf param echo"}, "LFI plus SSRF pivot to internal service", 2, "CRIT"),
    ({"behavioral auth boundary", "error disclosure"}, "auth bypass with error information disclosure", 2, "HIGH"),
]

_WAF_BYPASS_GAPS: Dict[str, List[Tuple[str, str, str]]] = {
    "cloudflare": [
        ("header-case-bypass", "X-Forwarded-For", "127.0.0.1"),
        ("content-type-bluff", "Content-Type", "application/x-www-form-urlencoded; charset=ibm037"),
        ("chunked-transfer", "Transfer-Encoding", "chunked"),
        ("http2-downgrade", "Upgrade", "h2c"),
        ("xff-spoof", "X-Real-IP", "127.0.0.1"),
    ],
    "aws waf": [
        ("header-injection", "X-Amzn-Trace-Id", ""),
        ("body-limit-bypass", "Content-Length", ""),
        ("charset-confusion", "Content-Type", "application/json; charset=utf-7"),
        ("xff-chain", "X-Forwarded-For", "127.0.0.1, 127.0.0.2"),
    ],
    "akamai": [
        ("request-id-bypass", "Akamai-Origin-Hop", "1"),
        ("pragma-no-cache", "Pragma", "no-cache"),
        ("accept-language-overflow", "Accept-Language", "en" + ",en" * 50),
    ],
    "imperva": [
        ("xff-localhost", "X-Forwarded-For", "127.0.0.1"),
        ("origin-spoof", "Origin", "https://localhost"),
        ("content-type-multipart", "Content-Type", "multipart/form-data; boundary=----WebKitFormBoundary"),
    ],
    "f5 big-ip": [
        ("x-f5-newconnpoolmember", "X-F5-New-Conn-Pool-Member", "1"),
        ("via-header", "Via", "1.1 localhost"),
        ("pragma-debug", "Pragma", "x-debug"),
    ],
    "modsecurity": [
        ("chunked-encoding", "Transfer-Encoding", "chunked, deflate"),
        ("unicode-normalization", "Accept-Charset", "utf-7"),
        ("multiline-header", "X-Custom-Header", "value\r\n injected"),
    ],
}

__all__ = [
    "_SLOW_SCANS",
    "_FAST_MODULES",
    "_FUSION_RULES",
    "_WAF_BYPASS_GAPS",
]
