"""Scan registry metadata.

This module stores option/label/function-name triples. Scanner.py binds the
function names after all scan functions have been defined, which avoids a
circular import between the registry and the scanner implementation.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, List, Tuple

from scanner.scans import category_for_option

SCAN_REGISTRY_SPECS: List[Tuple[str, str, str]] = [
    ('waf', 'waf detection', 'scan_waf_detection'),
    ('tech', 'technology fingerprint', 'scan_tech_fingerprint'),
    ('headers', 'security headers', 'scan_headers'),
    ('advheaders', 'advanced browser isolation headers', 'scan_security_advanced_headers'),
    ('xss', 'xss', 'scan_xss'),
    ('xssbypass', 'xss filter bypass', 'scan_xss_filter_bypass'),
    ('sqli', 'sqli error', 'scan_sqli'),
    ('timingsqli', 'sqli blind timing', 'scan_sqli_blind_timing'),
    ('lfi', 'lfi', 'scan_lfi'),
    ('cmdi', 'command injection', 'scan_cmdi'),
    ('ssti', 'ssti', 'scan_ssti'),
    ('nosql', 'nosql', 'scan_nosql'),
    ('ldap', 'ldap', 'scan_ldap'),
    ('proto', 'prototype pollution', 'scan_prototype_pollution'),
    ('crlf', 'crlf injection', 'scan_crlf'),
    ('redirect', 'open redirect', 'scan_open_redirect'),
    ('verbs', 'http verbs', 'scan_http_methods'),
    ('smuggling', 'http request smuggling', 'scan_http_smuggling'),
    ('cookies', 'cookie flags', 'scan_cookie_flags'),
    ('errors', 'error disclosure', 'scan_error_disclosure'),
    ('graphql', 'graphql introspection', 'scan_graphql'),
    ('listing', 'directory listing', 'scan_directory_listing'),
    ('backups', 'backup extensions', 'scan_backup_extensions'),
    ('hosthdr', 'host header reflection', 'scan_host_header'),
    ('robots', 'robots.txt', 'scan_robots_disclosure'),
    ('jwt', 'jwt surface', 'scan_jwt_issues'),
    ('corsreflect', 'cors arbitrary origin', 'scan_cors_arbitrary_origin'),
    ('xxe', 'xxe xml post', 'scan_xxe_post'),
    ('secrets', 'secret patterns in html', 'scan_secrets_in_response'),
    ('sitemapdeep', 'sitemap patterns', 'scan_sitemap_sensitive'),
    ('ipbypass', 'auth ip bypass headers', 'scan_auth_bypass_headers'),
    ('pathtrav', 'path traversal url', 'scan_path_traversal_url'),
    ('sri', 'external script sri', 'scan_external_script_sri'),
    ('httpdowngrade', 'http plaintext entry', 'scan_http_alternate_entry'),
    ('cachepoison', 'cache host poisoning', 'scan_cache_poison_headers'),
    ('openapi', 'openapi json', 'scan_openapi_json'),
    ('ssrf', 'ssrf param echo', 'scan_ssrf_param_echo'),
    ('ratelimit', 'rate limit detection', 'scan_rate_limit'),
    ('tls', 'tls quality', 'scan_tls_quality'),
    ('csp', 'csp analysis', 'scan_csp_analysis'),
    ('domxss', 'dom xss sinks', 'scan_dom_xss_sinks'),
    ('jssecrets', 'js file secrets', 'scan_js_secrets'),
    ('csrf', 'csrf form detection', 'scan_csrf_forms'),
    ('hpp', 'http parameter pollution', 'scan_hpp'),
    ('mixed', 'mixed content', 'scan_mixed_content'),
    ('s3', 's3 bucket exposure', 'scan_s3_exposure'),
    ('comments', 'html comment secrets', 'scan_html_comments'),
    ('idor', 'idor probe', 'scan_idor_probe'),
    ('sectxt', 'security.txt', 'scan_security_txt'),
    ('deser', 'deserialization surface', 'scan_deserialization'),
    ('lockout', 'login brute-force protection', 'scan_login_lockout'),
    ('upload', 'file upload surface', 'scan_file_upload_surface'),
    ('takeover', 'subdomain takeover', 'scan_subdomain_takeover'),
    ('clickjack', 'clickjacking advanced', 'scan_clickjacking_advanced'),
    ('corsfull', 'cors misconfiguration', 'scan_cors_misconfiguration'),
    ('jwtcrack', 'jwt weak secret', 'scan_jwt_crack'),
    ('jwtconf', 'jwt algorithm confusion', 'scan_jwt_alg_confusion'),
    ('race', 'race condition', 'scan_race_condition'),
    ('massassign', 'mass assignment', 'scan_mass_assignment'),
    ('gqldep', 'graphql deep scan', 'scan_graphql_deep'),
    ('srcmap', 'source map exposure', 'scan_source_maps'),
    ('oidc', 'oauth oidc misconfiguration', 'scan_oauth_oidc'),
    ('apiver', 'api versioning exposure', 'scan_api_versioning'),
    ('bizlogic', 'business logic', 'scan_business_logic'),
    ('entropy', 'entropy analysis', 'scan_entropy_analysis'),
    ('timing', 'timing attack', 'scan_timing_attack'),
    ('dkube', 'docker kubernetes exposure', 'scan_docker_kubernetes'),
    ('polyglot', 'polyglot injection', 'scan_polyglot_injection'),
    ('secondorder', 'second order injection', 'scan_second_order'),
    ('ws', 'websocket detection', 'scan_websocket'),
    ('dangle', 'dangling markup', 'scan_dangling_markup'),
    ('dnsrebind', 'dns rebinding surface', 'scan_dns_rebinding'),
    ('typeconf', 'parameter type confusion', 'scan_parameter_type_confusion'),
    ('log4j', 'log4shell jndi probe', 'scan_log4j'),
    ('actuator', 'spring actuator exposed', 'scan_spring_actuator'),
    ('cloudmeta', 'cloud metadata ssrf', 'scan_cloud_metadata'),
    ('offbyslash', 'nginx alias off-by-slash', 'scan_nginx_offbyslash'),
    ('verbtunnel', 'verb tunneling', 'scan_verb_tunneling'),
    ('typejuggle', 'php type juggling', 'scan_php_type_juggling'),
    ('cvefp', 'cve fingerprint', 'scan_cve_fingerprint'),
    ('subenum', 'subdomain enumeration', 'scan_subdomain_enum'),
    ('h2c', 'h2c upgrade smuggling', 'scan_h2c_smuggling'),
    ('cachekey', 'cache key poisoning', 'scan_cache_key_poisoning'),
    ('gopher', 'ssrf gopher/dict schemes', 'scan_ssrf_gopher_dict'),
    ('phpwrap', 'php wrapper LFI', 'scan_lfi_php_wrappers'),
    ('esi', 'esi injection', 'scan_esi_injection'),
    ('xslt', 'xslt injection', 'scan_xslt_injection'),
    ('depconf', 'dependency confusion', 'scan_dependency_confusion'),
    ('gqlsuggest', 'graphql field suggest', 'scan_graphql_field_suggest'),
    ('padoracle', 'padding oracle', 'scan_padding_oracle'),
    ('mine', 'hidden parameter discovery', 'scan_param_miner'),
    ('taint', 'js taint flow', 'scan_js_taint_flow'),
    ('sstifp', 'ssti engine fingerprint', 'scan_ssti_fingerprint'),
    ('cspgadget', 'csp bypass gadgets', 'scan_csp_bypass_gadgets'),
    ('csrfpoc', 'csrf poc generator', 'scan_csrf_poc'),
    ('jwtkid', 'jwt kid injection', 'scan_jwt_kid_injection'),
    ('unibp', 'unicode encoding bypass', 'scan_unicode_bypass'),
    ('srvtiming', 'server timing leak', 'scan_server_timing_leak'),
    ('nosqlblind', 'nosql blind oracle', 'scan_nosql_blind'),
    ('xssi', 'xssi json hijacking', 'scan_xssi'),
    ('rfd', 'reflected file download', 'scan_reflected_file_download'),
    ('nullbyte', 'null byte injection', 'scan_null_byte'),
    ('pathparam', 'path parameter injection', 'scan_path_param_injection'),
    ('methover', 'http method override', 'scan_http_method_override'),
    ('xpath', 'xpath injection', 'scan_xpath_injection'),
    ('rfi', 'remote file inclusion', 'scan_rfi'),
    ('accenum', 'account enumeration', 'scan_account_enumeration'),
    ('el', 'expression language injection', 'scan_expression_language'),
    ('ssi', 'ssi injection', 'scan_ssi_injection'),
    ('cssinj', 'css injection', 'scan_css_injection'),
    ('wshijack', 'websocket hijacking', 'scan_websocket_hijacking'),
    ('corspna', 'cors private network', 'scan_cors_private_network'),
    ('redos', 'redos', 'scan_redos'),
    ('ctconf', 'content-type confusion', 'scan_content_type_confusion'),
    ('sqliun', 'sqli union', 'scan_sqli_union'),
    ('jslibcve', 'js library cve', 'scan_js_library_cve'),
    ('cspt', 'client-side path traversal', 'scan_cspt'),
    ('referrerpolicy', 'referrer policy', 'scan_referrer_policy'),
    ('permissionspolicy', 'permissions policy', 'scan_permissions_policy'),
    ('reportinghdrs', 'reporting headers', 'scan_reporting_headers'),
    ('cachecontrol', 'cache control sensitive', 'scan_cache_control_sensitive'),
    ('cspscheme', 'csp scheme wildcards', 'scan_csp_scheme_wildcards'),
    ('appcache', 'appcache manifest', 'scan_appcache_manifest'),
    ('http2reset', 'http2 rapid reset surface', 'scan_http2_rapid_reset_surface'),
    ('srisameorigin', 'sri same origin libs', 'scan_sri_same_origin_libs'),
    ('dupcookie', 'duplicate setcookie', 'scan_duplicate_setcookie'),
    ('webauthn', 'webauthn config', 'scan_webauthn_config'),
    ('gqlalias', 'graphql alias dos', 'scan_graphql_alias_dos'),
    ('jwks', 'jwks endpoint', 'scan_jwks_endpoint'),
    ('http3down', 'http3 downgrade', 'scan_http3_downgrade'),
    ('cachepoisonxfh', 'cache poison xfh', 'scan_cache_poison_xfh'),
    ('oauthpkce', 'oauth pkce enforcement', 'scan_oauth_pkce_enforcement'),
    ('samlsig', 'saml sigwrap surface', 'scan_saml_sigwrap_surface'),
    ('redisunauth', 'redis unauth', 'scan_redis_unauth'),
    ('esunauth', 'elasticsearch unauth', 'scan_elasticsearch_unauth'),
    ('mongounauth', 'mongodb unauth', 'scan_mongodb_unauth'),
    ('k8setcd', 'kubernetes etcd kubelet', 'scan_kubernetes_etcd_kubelet'),
    ('coopeep', 'coop coep corp', 'scan_coop_coep_corp'),
    ('docpol', 'document policy', 'scan_document_policy'),
    ('clearsitedata', 'clear site data', 'scan_clear_site_data'),
    ('hstspreload', 'hsts preload readiness', 'scan_hsts_preload_readiness'),
    ('nextjsdata', 'nextjs data exposure', 'scan_nextjs_data'),
    ('nuxtpayload', 'nuxt payload exposure', 'scan_nuxt_payload'),
    ('manifests', 'manifest exposure', 'scan_manifest_exposure'),
    ('vcsm', 'vcs metadata', 'scan_vcs_metadata'),
    ('grpcreflect', 'grpc reflection', 'scan_grpc_reflection'),
    ('odatasoap', 'odata soap metadata', 'scan_odata_soap_metadata'),
    ('oauthstate', 'oauth state param', 'scan_oauth_state_param'),
    ('samlweakalg', 'saml weak algorithm', 'scan_saml_weak_alg'),
    ('wordpress', 'wordpress surface', 'scan_wordpress_surface'),
    ('laraveldebug', 'laravel django debug', 'scan_laravel_django_debug'),
    ('llmendpoints', 'llm endpoints', 'scan_llm_endpoints'),
    ('hasura', 'hasura admin', 'scan_hasura_admin'),
    ('gcpssrf', 'gcp metadata ssrf', 'scan_gcp_metadata_ssrf'),
    ('azureimds', 'azure oracle alibaba imds', 'scan_azure_oracle_alibaba_imds'),
    ('firebasedb', 'firebase open db', 'scan_firebase_open_db'),
    ('k8smanifest', 'k8s manifest exposure', 'scan_k8s_manifest_exposure'),
    ('jsendpoints', 'js endpoint extraction', 'scan_js_endpoints'),
    ('openapifuzz', 'openapi param fuzz', 'scan_openapi_fuzz'),
    ('clientstorage', 'client storage exposure', 'scan_client_storage_exposure'),
    ('trustfiles', 'well-known trust files', 'scan_well_known_trust_files'),
    ('policydrift', 'origin policy drift graph', 'scan_origin_policy_drift_graph'),
    ('pwresetpoison', 'password reset poisoning', 'scan_password_reset_poisoning'),
    ('jsonp', 'jsonp endpoints', 'scan_jsonp_endpoints'),
    ('defcreds', 'default credentials', 'scan_default_credentials'),
    ('logpoison', 'lfi log poisoning', 'scan_lfi_log_poisoning'),
    ('emailinject', 'email header injection', 'scan_email_header_injection'),
    ('xxeupload', 'xxe svg upload', 'scan_xxe_svg_upload'),
    ('wsfuzz', 'websocket fuzz', 'scan_websocket_fuzz'),
    ('sessfixation', 'session fixation', 'scan_session_fixation'),
    ('boolsqli', 'blind sqli boolean', 'scan_blind_sqli_boolean'),
    ('putwrite', 'put file write', 'scan_put_file_write'),
    ('dnszone', 'dns zone transfer', 'scan_dns_zone_transfer'),
    ('htmlinject', 'html injection', 'scan_html_injection'),
    ('tokenfresh', 'token freshness oracle', 'scan_token_freshness_oracle'),
    ('apiverscliff', 'api version cliff', 'scan_api_version_cliff'),
    ('respvariance', 'response variance oracle', 'scan_response_variance_oracle'),
    ('polyupload', 'polyglot file upload', 'scan_polyglot_file_upload'),
    ('jwtaudconf', 'jwt audience confusion', 'scan_jwt_audience_confusion'),
    ('cookiescope', 'subdomain cookie scope', 'scan_subdomain_cookie_scope'),
    ('aiprompt', 'ai prompt injection', 'scan_ai_prompt_injection'),
    ('llmbleed', 'llm context bleed', 'scan_llm_context_bleed'),
    ('llmrag', 'llm rag poisoning', 'scan_llm_rag_poisoning'),
    ('llmmemory', 'llm memorization leak', 'scan_llm_memorization_leak'),
    ('llmtokenbudget', 'llm token budget exhaustion', 'scan_llm_token_budget_exhaustion'),
    ('llmmultimodal', 'llm multimodal injection', 'scan_llm_multimodal_injection'),
    ('llmagentloop', 'llm agent loop detection', 'scan_llm_agent_loop_detection'),
    ('llmembedinv', 'llm embedding inversion', 'scan_llm_embedding_inversion'),
    ('llmjailbreak', 'llm jailbreak persistence', 'scan_llm_jailbreak_persistence'),
    ('llmsysprompt', 'llm system prompt map', 'scan_llm_system_prompt_map'),
    ('llmsmuggling', 'llm token smuggling', 'scan_llm_token_smuggling'),
    ('llmmcp', 'llm mcp exposure', 'scan_llm_mcp_exposure'),
    ('oobimap', 'oob imap ssrf', 'scan_oob_imap_ssrf'),
    ('ooblog4jhdr', 'oob log4shell headers', 'scan_oob_log4shell_headers'),
    ('swaggerxss', 'swagger ui xss', 'scan_swagger_ui_xss'),
    ('gqlbatch', 'graphql batch ratelimit bypass', 'scan_graphql_batch_ratelimit_bypass'),
    ('tecl', 'http desync te cl', 'scan_http_desync_te_cl'),
    ('sspp', 'prototype pollution server', 'scan_prototype_pollution_server'),
    ('behavauth', 'behavioral auth boundary', 'scan_behavioral_auth_boundary'),
    ('behavcache', 'behavioral cache confusion', 'scan_behavioral_cache_confusion'),
    ('stackcoherence', 'stack coherence', 'scan_stack_coherence'),
    ('deployage', 'deploy freshness', 'scan_deploy_freshness'),
    ('schemafuzz', 'schema fuzz', 'scan_schema_fuzz'),
    ('errorling', 'error linguistics', 'scan_error_linguistics'),
    ('deadcode', 'dead code paths', 'scan_dead_code_paths'),
    ('sessiondrift', 'session identity drift', 'scan_session_identity_drift'),
    ('tokenflow', 'token flow graph', 'scan_token_flow_graph'),
    ('wafbypass', 'waf bypass surface', 'scan_waf_bypass_surface'),
    ('selfconsist', 'self consistency', 'scan_self_consistency'),
    ('wasm', 'wasm analysis', 'scan_wasm_analysis'),
    ('importmap', 'import map injection', 'scan_import_map_injection'),
    ('fetchmeta', 'fetch metadata policy', 'scan_fetch_metadata_policy'),
    ('implicitflow', 'oauth implicit flow', 'scan_oauth_implicit_flow'),
    ('iisshort', 'iis short filename', 'scan_iis_shortname'),
    ('memcached', 'memcached exposure', 'scan_memcached_exposure'),
    ('webdav', 'webdav exposure', 'scan_webdav_exposure'),
    ('phpinfo', 'php info exposure', 'scan_php_info_exposure'),
    ('prometheus', 'prometheus exposure', 'scan_prometheus_exposure'),
    ('hashicorp', 'hashicorp exposure', 'scan_hashicorp_exposure'),
    ('trailers', 'http trailer injection', 'scan_http_trailer_injection'),
    ('urljuggle', 'ssrf url parser confusion', 'scan_ssrf_url_parser_confusion'),
    ('gqlsub', 'graphql subscriptions', 'scan_graphql_subscriptions'),
    ('ftpanon', 'ftp anonymous', 'scan_ftp_anonymous'),
    ('crlfsmuggle', 'crlf header smuggling', 'scan_crlf_header_smuggling'),
    ('corswild', 'cors wildcard credentialed', 'scan_cors_wildcard_credentialed'),
    ('raceamp', 'race window amplified', 'scan_race_window_amplified'),
    ('mergeslas', 'nginx merge slashes', 'scan_nginx_merge_slashes'),
    ('ssocas', 'sso cas exposure', 'scan_sso_cas_exposure'),
    ('domheadless', 'dom xss headless', 'scan_dom_xss_headless'),
    ('cspheadless', 'csp bypass headless', 'scan_csp_bypass_headless'),
    ('wsheadless', 'websocket headless', 'scan_websocket_headless'),
    ('clickheadless', 'clickjacking headless', 'scan_clickjacking_headless'),
    ('diffbaseline', 'baseline differential', 'scan_baseline_differential'),
    ('shadowroute', 'shadow route probe', 'scan_shadow_route_probe'),
    ('emaildns', 'email dns security', 'scan_email_dns_security'),
    ('mfabypass', 'mfa bypass', 'scan_mfa_bypass'),
    ('captcha', 'captcha weakness', 'scan_captcha_weakness'),
    ('pwpolicy', 'password policy', 'scan_password_policy'),
    ('deepgit', 'deep git exposure', 'scan_deep_git_exposure'),
    ('smtprelay', 'smtp open relay', 'scan_smtp_relay'),
    ('dnscaa', 'dns caa record', 'scan_dns_caa'),
    ('ctlogs', 'ct log enumeration', 'scan_ct_log_enum'),
    ('contentneg', 'content negotiation attack', 'scan_content_negotiation'),
    ('deserchains', 'deserialization gadget chain', 'scan_deserialization_chains'),
    ('depcve', 'dependency version cve', 'scan_dependency_version_cve'),
    ('semequiv', 'http semantic equivalence', 'scan_http_semantic_equivalence'),
    ('pdg', 'parameter dependency graph', 'scan_param_dependency_graph'),
    ('mvfusion', 'multi-vector fusion', 'scan_multi_vector_fusion'),
    ('timecov', 'timing covariance oracle', 'scan_timing_covariance_oracle'),
    ('jwtjku', 'jwt jku x5u injection', 'scan_jwt_jku_x5u'),
    ('gqlintrob', 'graphql introspection bypass', 'scan_graphql_introspection_bypass'),
    ('atchain', 'account takeover chain', 'scan_account_takeover_chain'),
    ('killchain', 'kill chain oracle', 'scan_kill_chain_oracle'),
    ('bfla', 'broken function level auth', 'scan_bfla'),
    ('jsonrpc', 'jsonrpc exposure', 'scan_jsonrpc_exposure'),
    ('sse', 'sse injection', 'scan_sse_injection'),
    ('swsurface', 'service worker surface', 'scan_service_worker_surface'),
    ('gqlmutate', 'graphql mutation abuse', 'scan_graphql_mutation_abuse'),
    ('wpauto27956', 'zd wp automatic cve 2024 27956', 'scan_zd_wp_automatic_cve_2024_27956'),
    ('grafanapath', 'zd grafana legacy plugin traversal', 'scan_zd_grafana_legacy_plugin_traversal'),
    ('rsssl10924', 'zd really simple security cve 2024 10924', 'scan_zd_really_simple_security_cve_2024_10924'),
    ('jenkins43044', 'zd jenkins file read cve 2024 43044', 'scan_zd_jenkins_file_read_cve_2024_43044'),
    ('wug6670', 'zd whatsupgold sqli cve 2024 6670', 'scan_zd_whatsupgold_sqli_cve_2024_6670'),
    ('roundcube37383', 'zd roundcube xss cve 2024 37383', 'scan_zd_roundcube_xss_cve_2024_37383'),
    ('edimax1316', 'zd edimax camera cve 2025 1316', 'scan_zd_edimax_camera_cve_2025_1316'),
    ('laravel52301', 'zd laravel env manipulation cve 2024 52301', 'scan_zd_laravel_env_manipulation_cve_2024_52301'),
    ('sp38094', 'zd sharepoint deser cve 2024 38094', 'scan_zd_sharepoint_deser_cve_2024_38094'),
    ('cleo55956', 'zd cleo harmony cve 2024 55956', 'scan_zd_cleo_harmony_cve_2024_55956'),
    ('behavioral_matrix', 'behavioral contradiction matrix', 'scan_behavioral_contradiction_matrix'),
    ('appmodel', 'application model synthesis', 'synthesize_application_model'),
    ('causal_proof', 'causal security proof synthesis', 'synthesize_causal_security_proof'),
    ('auth_falsify', 'authorization invariant falsification', 'falsify_authorization_invariants'),
    ('auth_graph', 'authorization graph topology', 'discover_authorization_graph_exploits'),
    ('race_window', 'concurrent race window', 'discover_race_window'),
    ('smuggling_oracle', 'http request smuggling oracle', 'discover_smuggling_oracle'),
    ('h2_desync', 'h2 binary desync', 'discover_h2_desync'),
    ('ssti_oracle', 'ssti template injection', 'discover_ssti_oracle'),
    ('cache_poison', 'web cache poisoning', 'discover_cache_poisoning_oracle'),
    ('graphql_oracle', 'graphql attack surface', 'discover_graphql_oracle'),
    ('xxe_oracle', 'xxe injection', 'discover_xxe_oracle'),
    ('pp_oracle', 'prototype pollution oracle', 'discover_prototype_pollution_oracle'),
    ('session_oracle', 'session token oracle', 'discover_session_oracle'),
    ('consistency', 'response consistency', 'scan_response_consistency'),
    ('deception', 'deception detection', 'scan_deception_detection'),
    ('parammatrix', 'parameter interaction matrix', 'scan_param_interaction_matrix'),
    ('paymin', 'payload minimizer', 'scan_payload_minimizer'),
    ('diffauth', 'differential auth check', 'scan_differential_auth'),
    ('ghostparams', 'ghost parameter discovery', 'scan_ghost_params'),
    ('formmutate', 'form mutation fuzzer', 'scan_form_mutation'),
    ('ssrftiming', 'ssrf timing oracle', 'scan_ssrf_timing_oracle'),
    ('breachoracle', 'breach compression oracle', 'scan_breach_oracle'),
    ('cachetimeenum', 'cache timing user enum', 'scan_cache_timing_enum'),
    ('smuggling', 'http request smuggling', 'scan_http_request_smuggling'),
    ('racecondition', 'race condition window legacy', 'scan_race_condition_window'),
    ('cachedeception', 'web cache deception', 'scan_web_cache_deception'),
    ('protopollution', 'prototype pollution extended', 'scan_prototype_pollution'),
    ('hostheader', 'host header injection', 'scan_host_header_injection'),
    ('xffbypass', 'xff ip bypass', 'scan_xff_ip_bypass'),
    ('backupfiles', 'backup file discovery', 'scan_backup_file_discovery'),
    ('gitexposure', 'git repository exposure', 'scan_git_exposure'),
    ('envexposure', 'env file exposure', 'scan_env_file_exposure'),
    ('nosqli', 'nosql injection', 'scan_nosql_injection'),
    ('ldapi', 'ldap injection', 'scan_ldap_injection'),
    ('csvinjection', 'csv formula injection', 'scan_csv_injection'),
    ('jwtalg', 'jwt algorithm confusion extended', 'scan_jwt_alg_confusion'),
    ('graphql', 'graphql attack surface', 'scan_graphql_surface'),
    ('apiversionbypass', 'api version bypass', 'scan_api_version_bypass'),
    ('methodoverride', 'http method override extended', 'scan_http_method_override'),
    ('corsnull', 'cors null origin', 'scan_cors_null_origin'),
    ('intoverflow', 'integer overflow params', 'scan_integer_overflow'),
    ('domsecrets', 'dom secret discovery', 'scan_dom_secrets'),
    ('nuclei_lite', 'nuclei-lite templates', 'scan_nuclei_lite_templates'),
    ('frontier', 'frontier crawler', 'scan_frontier_crawler'),
    ('formflow', 'form workflow scanner', 'scan_form_workflows'),
    ('domrecord', 'dom browser recorder', 'scan_dom_browser_recorder'),
    ('openapi_routes', 'openapi route tester', 'scan_openapi_route_tester'),
    ('wp_plugins', 'wordpress plugin theme detector', 'scan_wordpress_plugin_theme_detector'),
    ('wp_users', 'wordpress user enumeration', 'scan_wordpress_user_enum'),
    ('wp_xmlrpc', 'wordpress xmlrpc exposure', 'scan_wordpress_xmlrpc'),
    ('laravel_env_deep', 'laravel env debug deep', 'scan_laravel_env_debug_deep'),
    ('django_debug', 'django debug exposure', 'scan_django_debug_deep'),
    ('actuator_deep', 'spring actuator deep', 'scan_spring_actuator_deep'),
    ('jenkins_exposure', 'jenkins exposure', 'scan_jenkins_exposure'),
    ('grafana_exposure', 'grafana exposure', 'scan_grafana_exposure'),
    ('k8s_dashboard', 'kubernetes dashboard exposure', 'scan_kubernetes_dashboard_exposure'),
    ('docker_registry', 'docker registry exposure', 'scan_docker_registry_exposure'),
    ('observability_stack', 'observability stack exposure', 'scan_observability_stack_exposure'),
    ('admin_finder', 'admin panel finder', 'scan_admin_panel_finder'),
    ('backup_smart', 'backup archive smart discovery', 'scan_backup_archive_smart'),
    ('cloud_buckets', 'cloud bucket exposure', 'scan_cloud_bucket_exposure'),
    ('firebase_deep', 'firebase deep exposure', 'scan_firebase_exposure_deep'),
    ('supabase', 'supabase exposure', 'scan_supabase_exposure'),
    ('cloud_blob_urls', 'cloud blob url detection', 'scan_cloud_blob_url_detection'),
    ('oauth_redirects', 'oauth redirect uri weakness', 'scan_oauth_redirect_uri_weakness'),
    ('saml_metadata', 'saml metadata security', 'scan_saml_metadata_security'),
    ('ws_auth_cors', 'websocket auth cors', 'scan_websocket_auth_cors'),
    ('cors_preflight_cache', 'cors preflight cache weakness', 'scan_cors_preflight_cache_weakness'),
    ('csp_suggestions', 'csp bypass suggestions', 'scan_csp_bypass_suggestions'),
    ('sectxt_parser', 'security txt parser', 'scan_security_txt_parser'),
    ('dep_license_risk', 'dependency license risk', 'scan_dependency_license_risk'),
    ('sourcemap_secrets', 'sourcemap secret scanner', 'scan_sourcemap_secret_scanner'),
    ('robots_score', 'robots sitemap scoring', 'scan_robots_sitemap_scoring'),
    ('gqlschema', 'graphql schema aware', 'scan_graphql_schema_aware'),
    ('sqlmap_export', 'sqlmap handoff export', 'scan_sqlmap_export'),
    ('fuzzer', 'path fuzzer', 'scan_fuzzer_mode'),
    ('source_scan', 'source code static scan', 'scan_source_code_mode'),
    ('sbom_scan', 'sbom dependency scan', 'scan_local_dependency_mode'),
    ('servicedisc', 'service discovery', 'scan_service_discovery'),
    ('tlsdeep', 'tls deep scan', 'scan_tls_deep'),
    ('wafdeep', 'waf deep fingerprint', 'scan_waf_fingerprint_deep'),
    ('sourcemap_recon', 'sourcemap reconstruction', 'scan_sourcemap_reconstruction'),
    ('inventory', 'dependency inventory', 'scan_dependency_inventory'),
    ('inventory_cves', 'inventory cve match', 'scan_inventory_cve_match'),
    ('authprofile', 'authenticated profile diff', 'scan_auth_profile_state'),
    ('adaptive_recs', 'adaptive recommendations', 'scan_adaptive_recommendations'),
    ('self_debug', 'scanner self debug', 'scan_self_debug_gaps'),
    ('target_playbooks', 'target playbooks', 'scan_target_playbooks'),
]

def build_scan_registry(symbols: Dict[str, Any]) -> List[Tuple[str, str, Callable]]:
    registry: List[Tuple[str, str, Callable]] = []
    missing: List[str] = []
    for option, label, fn_name in SCAN_REGISTRY_SPECS:
        fn = symbols.get(fn_name)
        if not callable(fn):
            missing.append(fn_name)
            continue
        registry.append((option, label, fn))
    if missing:
        raise RuntimeError("missing scan registry functions: " + ", ".join(sorted(missing)))
    return registry

def registry_category_counts(entries: List[Tuple[str, str, Callable]]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for option, _, _ in entries:
        category = category_for_option(option)
        counts[category] = counts.get(category, 0) + 1
    return counts

__all__ = ["SCAN_REGISTRY_SPECS", "build_scan_registry", "registry_category_counts"]
