"""Signatures data for Apex."""

from __future__ import annotations

from typing import Dict, List, Tuple

_JS_LIB_CVES: Dict[str, List[Tuple[str, str, str, str]]] = {
    "jquery": [
        ("1.6.3",  "CVE-2011-4969",   "MED",  "XSS via location.hash selector"),
        ("1.9.0",  "CVE-2012-6708",   "MED",  "selector parsing XSS"),
        ("3.0.0",  "CVE-2015-9251",   "MED",  "XSS via cross-domain ajax with text/javascript response"),
        ("3.4.0",  "CVE-2019-11358",  "HIGH", "prototype pollution in jQuery.extend(true, ...)"),
        ("3.5.0",  "CVE-2020-11022",  "HIGH", "XSS via .html()/.append() with attacker HTML"),
        ("3.5.0",  "CVE-2020-11023",  "HIGH", "XSS via <option> tag injection"),
    ],
    "jquery-ui": [
        ("1.12.0", "CVE-2016-7103",   "MED",  "XSS in dialog closeText option"),
        ("1.13.0", "CVE-2021-41182",  "MED",  "XSS in altField of datepicker"),
        ("1.13.0", "CVE-2021-41183",  "MED",  "XSS in various widgets"),
        ("1.13.0", "CVE-2021-41184",  "MED",  "XSS in position of() option"),
    ],
    "angularjs": [
        ("1.5.0",  "ANGULARJS-SANDBOX-BYPASS", "HIGH", "expression sandbox bypass (no active CVE mapping)"),
        ("1.6.0",  "CVE-2017-1002101","HIGH", "sandbox bypass via charset property"),
        ("1.8.0",  "CVE-2019-10768",  "HIGH", "prototype pollution via merge"),
        ("99.0.0", "ANGULARJS-EOL",   "HIGH", "AngularJS reached EOL Jan 2022; no further security fixes"),
    ],
    "lodash": [
        ("4.17.5",  "CVE-2018-3721",  "MED",  "prototype pollution via defaultsDeep"),
        ("4.17.11", "CVE-2018-16487", "HIGH", "prototype pollution via merge/mergeWith/defaultsDeep"),
        ("4.17.12", "CVE-2019-10744", "HIGH", "prototype pollution via defaultsDeep (deeper)"),
        ("4.17.20", "CVE-2020-8203",  "HIGH", "prototype pollution via zipObjectDeep"),
        ("4.17.21", "CVE-2021-23337", "HIGH", "command injection via template"),
    ],
    "moment": [
        ("2.19.3", "CVE-2017-18214",  "MED",  "ReDoS in rfc2822 parsing"),
        ("2.29.2", "CVE-2022-24785",  "HIGH", "path traversal in locale loading (Node)"),
        ("2.29.4", "CVE-2022-31129",  "HIGH", "ReDoS via long input strings"),
    ],
    "bootstrap": [
        ("3.4.0",  "CVE-2018-14040",  "MED",  "XSS in collapse data-parent"),
        ("3.4.0",  "CVE-2018-14041",  "MED",  "XSS in scrollspy data-target"),
        ("3.4.0",  "CVE-2018-14042",  "MED",  "XSS in tooltip data-container"),
        ("3.4.1",  "CVE-2019-8331",   "MED",  "XSS in tooltip / popover data-template"),
        ("4.3.1",  "CVE-2019-8331",   "MED",  "XSS in tooltip / popover data-template"),
    ],
    "handlebars": [
        ("4.0.14", "CVE-2019-19919",  "HIGH", "prototype pollution via constructor"),
        ("4.5.3",  "CVE-2019-20920",  "HIGH", "RCE via lookup helper"),
        ("4.7.7",  "CVE-2021-23369",  "HIGH", "RCE via compiled templates with strict:false"),
        ("4.7.7",  "CVE-2021-23383",  "HIGH", "RCE via prototype lookup in select"),
    ],
    "ckeditor": [
        ("4.16.0", "CVE-2021-26271",  "HIGH", "XSS via crafted HTML in clipboard plugin"),
        ("4.17.0", "CVE-2021-37695",  "HIGH", "XSS via crafted HTML in fakeobjects plugin"),
        ("4.24.0", "CVE-2024-24816",  "HIGH", "XSS via specially crafted input"),
    ],
    "tinymce": [
        ("5.10.0", "TINYMCE-LEGACY-XSS", "MED", "various XSS in older TinyMCE 4/5"),
        ("6.4.2",  "CVE-2023-29528",  "MED",  "XSS via crafted media element"),
        ("6.7.3",  "CVE-2023-45818",  "HIGH", "XSS via getContent API"),
    ],
    "vue": [
        ("2.5.17", "CVE-2018-20235",  "MED",  "ReDoS in template compiler"),
        ("3.0.0",  "VUE2-EOL",        "MED",  "Vue 2 reached EOL Dec 2023; migrate to Vue 3"),
    ],
    "ember": [
        ("3.4.5",  "CVE-2018-3717",   "MED",  "XSS via input bindings"),
    ],
    "knockout": [
        ("3.5.1",  "CVE-2019-14862",  "MED",  "XSS via attribute bindings"),
    ],
    "prototype": [
        ("1.7.4",  "PROTOTYPE-EOL",   "MED",  "Prototype.js abandoned; multiple legacy XSS"),
    ],
    "yui": [
        ("99.0.0", "YUI-EOL",         "HIGH", "YUI is end-of-life since 2014; remove and replace"),
    ],
    "mustache": [
        ("2.2.1",  "CVE-2015-8862",   "MED",  "XSS via {{{...}}} unescaped output"),
    ],
    "underscore": [
        ("1.12.1", "CVE-2021-23358",  "HIGH", "code injection via template function"),
    ],
    "dompurify": [
        ("2.0.17", "CVE-2020-26870",  "HIGH", "XSS via mutation in foreignObject"),
        ("2.2.4",  "CVE-2020-26891",  "HIGH", "XSS via mXSS in browsers"),
        ("2.4.0",  "CVE-2022-23631",  "MED",  "XSS via nested template tags"),
        ("3.0.9",  "CVE-2024-45801",  "HIGH", "XSS via prototype pollution gadget"),
    ],
    "marked": [
        ("0.6.2",  "CVE-2017-16114",  "MED",  "ReDoS in inline.heading"),
        ("4.0.10", "CVE-2022-21680",  "MED",  "ReDoS in block heading"),
        ("4.0.10", "CVE-2022-21681",  "MED",  "ReDoS in inline rules"),
    ],
    "axios": [
        ("0.21.1", "CVE-2020-28168",  "MED",  "SSRF via crafted URL"),
        ("0.21.2", "CVE-2021-3749",   "MED",  "ReDoS via no_proxy header"),
        ("1.6.0",  "CVE-2023-45857",  "HIGH", "CSRF token leak via XSRF-TOKEN header to other domains"),
    ],
    "bootstrap-vue": [
        ("2.21.2", "CVE-2021-23197",  "MED",  "XSS via b-form-checkbox / b-form-radio"),
    ],
    "swagger-ui": [
        ("3.0.13", "CVE-2018-25031",  "MED",  "XSS via crafted URL"),
        ("4.1.3",  "CVE-2021-46708",  "MED",  "XSS via spec parameter"),
    ],
    "select2": [
        ("4.0.6",  "CVE-2016-10744",  "MED",  "XSS via templateResult"),
    ],
}

_STACK_SIGNALS: Dict[str, List[str]] = {
    "wordpress": ["wordpress", "wp-content", "wp-login", "wordpress_", "wp-settings-"],
    "laravel":   ["laravel", "illuminate", "laravel_session", "illuminate_"],
    "django":    ["django", "csrfmiddlewaretoken", "csrftoken", "x-frame-options: sameorigin"],
    "nextjs":    ["next.js", "_next/", "nextjs"],
    "nuxt":      ["nuxt", "__nuxt"],
    "vue":       ["vue.js", "vue/", "__vue"],
    "react":     ["react", "reactdom", "_react"],
    "aspnet":    ["asp.net", "x-aspnet", "x-aspnetmvc", "x-aspnet-version", "asp.net_sessionid", ".aspx"],
    "drupal":    ["drupal", "sites/all"],
    "rails":     ["ruby on rails", "x-rails", "x-request-id", "_rails_session", "x-runtime"],
    "express":   ["express", "node.js server", "x-powered-by: express", "connect.sid"],
    "spring":    ["spring", "x-application-context", "jsessionid"],
    "node":      ["node.js", "nodejs"],
    "go":        ["go http", "gorilla"],
    "ruby":      ["ruby", "rack"],
    "php":       ["php", "x-powered-by: php", "phpsessid", ".php"],
}

_KEV_META: Dict[str, Dict] = {
    "zd palo globalprotect":       {"kev_added": "2024-04-12", "cvss": "10.0", "ransomware": "yes",  "due": "2024-05-03"},
    "zd teamcity auth bypass":     {"kev_added": "2024-03-07", "cvss": "9.8",  "ransomware": "yes",  "due": "2024-03-28"},
    "zd ivanti connectsecure":     {"kev_added": "2024-01-10", "cvss": "8.2",  "ransomware": "yes",  "due": "2024-01-31"},
    "zd moveit transfer":          {"kev_added": "2023-06-02", "cvss": "9.8",  "ransomware": "yes",  "due": "2023-06-23"},
    "zd jenkins cli read":         {"kev_added": "2024-01-29", "cvss": "9.8",  "ransomware": "yes",  "due": "2024-02-19"},
    "zd php cgi argv":             {"kev_added": "2024-07-09", "cvss": "9.8",  "ransomware": "yes",  "due": "2024-07-30"},
    "zd openssh regression":      {"kev_added": "2024-07-01", "cvss": "8.1",  "ransomware": "no",   "due": "2024-07-22"},
    "zd confluence ssti":          {"kev_added": "2024-01-16", "cvss": "10.0", "ransomware": "yes",  "due": "2024-02-06"},
    "zd connectwise screenconnect":{"kev_added": "2024-02-21", "cvss": "10.0", "ransomware": "yes",  "due": "2024-02-29"},
    "zd citrix bleed":             {"kev_added": "2023-10-18", "cvss": "9.4",  "ransomware": "yes",  "due": "2023-11-08"},
    "zd gitlab pwreset":           {"kev_added": "2024-01-12", "cvss": "10.0", "ransomware": "no",   "due": "2024-02-02"},
    "zd apache activemq":          {"kev_added": "2023-11-02", "cvss": "10.0", "ransomware": "yes",  "due": "2023-11-23"},
    "zd checkpoint vpn":           {"kev_added": "2024-05-30", "cvss": "8.6",  "ransomware": "yes",  "due": "2024-06-20"},
    "zd fortios auth bypass":      {"kev_added": "2025-01-14", "cvss": "9.6",  "ransomware": "yes",  "due": "2025-02-04"},
    "zd crushftp ssti":            {"kev_added": "2024-05-01", "cvss": "9.8",  "ransomware": "yes",  "due": "2024-05-22"},
    "zd sonicwall sma":            {"kev_added": "2025-01-23", "cvss": "9.8",  "ransomware": "yes",  "due": "2025-02-13"},
    "zd f5 bigip icontrol":        {"kev_added": "2022-05-10", "cvss": "9.8",  "ransomware": "yes",  "due": "2022-05-31"},
    "zd nextjs middleware bypass":  {"kev_added": "2025-03-25", "cvss": "9.1",  "ransomware": "no",   "due": "2025-04-15"},
    "zd fortimanager fortijump":   {"kev_added": "2024-10-23", "cvss": "9.8",  "ransomware": "yes",  "due": "2024-11-13"},
    "zd zimbra rce":               {"kev_added": "2024-10-02", "cvss": "9.8",  "ransomware": "no",   "due": "2024-10-23"},
    "zd veeam backup rce":         {"kev_added": "2024-09-10", "cvss": "9.8",  "ransomware": "yes",  "due": "2024-10-01"},
    "zd tomcat partial put":       {"kev_added": "2025-03-21", "cvss": "9.8",  "ransomware": "yes",  "due": "2025-04-11"},
    "zd ivanti cs stackoverflow":  {"kev_added": "2025-04-03", "cvss": "9.0",  "ransomware": "yes",  "due": "2025-04-24"},
    "zd sap netweaver vc upload":  {"kev_added": "2025-04-28", "cvss": "10.0", "ransomware": "yes",  "due": "2025-05-19"},
    "zd cisco iosxe webui":        {"kev_added": "2023-10-16", "cvss": "10.0", "ransomware": "yes",  "due": "2023-11-06"},
    "zd apache ofbiz screen render":{"kev_added": "2024-09-04","cvss": "9.8",  "ransomware": "yes",  "due": "2024-09-25"},
    "zd veeam backup deser":       {"kev_added": "2024-09-10", "cvss": "9.8",  "ransomware": "yes",  "due": "2024-10-01"},
    "zd fortios fgfm fmtstring":   {"kev_added": "2024-02-09", "cvss": "9.8",  "ransomware": "yes",  "due": "2024-03-01"},
    "zd cups browsed":             {"kev_added": "2024-09-27", "cvss": "9.9",  "ransomware": "no",   "due": "2024-10-18"},
    "zd spring path traversal":    {"kev_added": "2024-09-20", "cvss": "7.5",  "ransomware": "no",   "due": "2024-10-11"},
    "zd solarwinds servu":         {"kev_added": "2024-06-25", "cvss": "7.5",  "ransomware": "yes",  "due": "2024-07-16"},
    "zd zimbra postjournal":       {"kev_added": "2024-10-02", "cvss": "9.8",  "ransomware": "no",   "due": "2024-10-23"},
    "zd servicenow jelly":         {"kev_added": "2024-07-26", "cvss": "9.3",  "ransomware": "no",   "due": "2024-08-16"},
    "zd activemq cve 2026 34197":  {"kev_added": "2026-04-16", "cvss": "9.8",  "ransomware": "yes",  "due": "2026-04-30"},
    "zd sharepoint cve 2026 32201":{"kev_added": "2026-04-16", "cvss": "9.0",  "ransomware": "yes",  "due": "2026-04-30"},
    "zd sharepoint toolpane chain":{"kev_added": "2026-04-16", "cvss": "8.8",  "ransomware": "yes",  "due": "2026-04-30"},
    "zd langflow cve 2026 33017":  {"kev_added": "2026-04-10", "cvss": "9.8",  "ransomware": "no",   "due": "2026-04-30"},
    "zd fortinet cve 2026 21643":  {"kev_added": "2026-04-14", "cvss": "9.3",  "ransomware": "yes",  "due": "2026-04-30"},
    "zd citrix bleed 2 cve 2025 5777":{"kev_added": "2026-04-17", "cvss": "9.4", "ransomware": "yes","due": "2026-05-08"},
    "zd oracle ebs cve 2025 61882":{"kev_added": "2026-04-15", "cvss": "9.8",  "ransomware": "no",   "due": "2026-05-06"},
    "zd exchange cve 2023 21529":  {"kev_added": "2023-02-14", "cvss": "8.8",  "ransomware": "yes",  "due": "2023-03-07"},
    "zd ingress nginx cve 2025 1974":   {"kev_added": "2025-03-24", "cvss": "9.8",  "ransomware": "no",   "due": "2025-04-14"},
    "zd cisco smartlic cve 2024 20439": {"kev_added": "2025-03-20", "cvss": "9.8",  "ransomware": "no",   "due": "2025-04-10"},
    "zd dlink nas cve 2024 10914":      {"kev_added": "2024-11-13", "cvss": "9.8",  "ransomware": "no",   "due": "2024-12-04"},
    "zd apache httpd cve 2024 38475":   {"kev_added": "2024-08-05", "cvss": "9.1",  "ransomware": "no",   "due": "2024-08-26"},
    "zd parquet cve 2025 30065":        {"kev_added": "2025-04-02", "cvss": "10.0", "ransomware": "no",   "due": "2025-04-23"},
}

_SENSITIVE_PATHS = [
    "/.env", "/.env.local", "/.env.production", "/.env.backup", "/.env.old",
    "/.env.dev", "/.env.staging", "/.env.example",
    "/config.json", "/config.yml", "/config.yaml", "/config.php",
    "/settings.json", "/settings.py", "/local_settings.py",
    "/application.properties", "/application.yml", "/application.yaml",
    "/appsettings.json", "/appsettings.Development.json",
    "/secrets.json", "/secrets.yml", "/.secret", "/credentials.json",
    "/database.yml", "/database.json", "/db.json",
    "/.aws/credentials", "/.aws/config",
    "/.git/config", "/.git/HEAD", "/.git/COMMIT_EDITMSG",
    "/.git/refs/heads/main", "/.git/refs/heads/master",
    "/.gitignore", "/.gitattributes",
    "/.svn/entries", "/.svn/wc.db",
    "/.hg/hgrc", "/CVS/Root",
    "/backup.sql", "/backup.sql.gz", "/dump.sql", "/db_dump.sql",
    "/database.sql", "/data.sql", "/data.sql.gz",
    "/backup.zip", "/backup.tar.gz", "/backup.tar",
    "/site.zip", "/www.zip", "/html.tar.gz", "/public.zip",
    "/db.tar.gz", "/files.tar.gz",
    "/backup.bak", "/config.bak", "/index.bak",
    "/phpinfo.php", "/info.php", "/test.php", "/php.php",
    "/server-status", "/server-info",
    "/.htaccess", "/.htpasswd", "/web.config", "/httpd.conf",
    "/nginx.conf", "/lighttpd.conf",
    "/.DS_Store", "/Thumbs.db",
    "/crossdomain.xml", "/clientaccesspolicy.xml",
    "/package.json", "/package-lock.json", "/yarn.lock",
    "/node_modules/.package-lock.json",
    "/.npmrc", "/.yarnrc", "/.nvmrc",
    "/webpack.config.js", "/vite.config.js", "/next.config.js",
    "/.babelrc", "/tsconfig.json", "/jsconfig.json",
    "/composer.json", "/composer.lock",
    "/vendor/autoload.php", "/vendor/composer/installed.json",
    "/requirements.txt", "/Pipfile", "/Pipfile.lock", "/pyproject.toml",
    "/setup.py", "/setup.cfg",
    "/Gemfile", "/Gemfile.lock",
    "/pom.xml", "/build.gradle",
    "/wp-login.php", "/wp-admin/", "/wp-config.php",
    "/wp-content/debug.log", "/wp-json/wp/v2/users",
    "/xmlrpc.php", "/wp-cron.php",
    "/administrator/", "/admin/", "/admin/login", "/admin/index.php",
    "/user/login", "/login", "/signin", "/sign-in",
    "/joomla/administrator/", "/typo3/", "/drupal/",
    "/magento/admin/", "/bitrix/admin/",
    "/api/swagger.json", "/api/swagger.yaml",
    "/api-docs", "/api-docs/swagger.json",
    "/v2/api-docs", "/v3/api-docs",
    "/swagger-ui.html", "/swagger-ui/index.html",
    "/swagger/index.html", "/api/swagger-ui.html",
    "/openapi.json", "/openapi.yaml",
    "/redoc", "/redoc/",
    "/graphql", "/graphiql", "/api/graphql", "/graphql/console",
    "/wsdl", "/?wsdl", "/service.wsdl", "/api/wsdl",
    "/actuator", "/actuator/env", "/actuator/health", "/actuator/info",
    "/actuator/metrics", "/actuator/mappings", "/actuator/beans",
    "/actuator/gateway/routes", "/actuator/httptrace",
    "/actuator/logfile", "/actuator/threaddump", "/actuator/heapdump",
    "/actuator/configprops", "/actuator/auditevents",
    "/actuator/scheduledtasks", "/actuator/caches",
    "/debug", "/trace", "/status", "/health", "/healthz", "/readyz",
    "/metrics", "/console", "/dashboard",
    "/_ah/admin", "/_admin", "/_debug",
    "/django-admin/", "/django-admin/login/",
    "/__debug__/", "/profiler",
    "/_profiler/phpinfo", "/_profiler/open",
    "/telescope/requests", "/horizon/",
    "/flower/", "/celery/",
    "/jenkins/login", "/jenkins/", "/ci/login",
    "/sonar/", "/.travis.yml", "/.circleci/config.yml",
    "/Jenkinsfile", "/Dockerfile", "/docker-compose.yml",
    "/k8s/", "/kubernetes/", "/.kube/config",
    "/helm/", "/charts/",
    "/robots.txt", "/sitemap.xml", "/sitemap_index.xml",
    "/.well-known/security.txt", "/.well-known/openid-configuration",
    "/.well-known/jwks.json", "/.well-known/oauth-authorization-server",
    "/s3.json", "/aws.json", "/gcp.json",
    "/.s3cfg", "/.boto",
    "/api/json", "/info", "/version", "/build",
    "/console/login", "/admin/config", "/admin/settings",
    "/__webpack_hmr", "/__webpack_dev_server__",
    "/trace.axd", "/elmah.axd", "/ScriptResource.axd",
    "/glimpse.axd", "/mini-profiler-resources/results",
    "/log/access.log", "/log/error.log", "/logs/app.log",
    "/error_log", "/access_log", "/debug.log",
    "/WEB-INF/web.xml", "/WEB-INF/classes/",
    "/META-INF/MANIFEST.MF", "/struts.xml", "/applicationContext.xml",
]

_SQL_ERRORS = [
    r"sql syntax",
    r"mysql_fetch",
    r"warning:\s*mysql",
    r"mysqli_",
    r"postgresql query failed",
    r"pg_query\(\)",
    r"unclosed quotation mark after the character string",
    r"quoted string not properly terminated",
    r"ora-\d{5}",
    r"microsoft ole db provider",
    r"odbc sql server driver",
    r"sqlite3\.operationalerror",
    r"sqlite_exception",
    r"driver.*sql",
    r"sqlite error",
    r"sqlstate",
]

_ERROR_DISCLOSURE = [
    r"traceback \(most recent call last\)",
    r"exception in thread",
    r"fatal error",
    r"uncaught exception",
    r"at [a-z0-9_.]+\([a-z]+\.java:\d+\)",
    r"system\.web\.httpexception",
    r"microsoft \.net framework",
    r"postgresql.*error",
    r"sqlite3\.operationalerror",
    r"odbc driver",
    r"sqlitedriver",
    r"raise com\..*exception",
    r"nested exception is",
    r"caused by: java\.",
    r"php warning:",
    r"php fatal error:",
    r"php parse error:",
    r"undefined index:",
    r"undefined variable",
    r"stack trace:",
]

_NOSQL_ERRORS = [
    r"cannot read property",
    r"failed to parse",
    r"unexpected token",
    r"mongoerror",
    r"mongodb\.driver",
    r"bson",
    r"invalid.*objectid",
    r"\$where",
]

_WAF_SIGNATURES = {
    "Cloudflare":     [r"cf-ray", r"__cfduid", r"cloudflare"],
    "Akamai":         [r"akamai", r"x-akamai-request-id", r"ak_bmsc"],
    "AWS WAF":        [r"x-amzn-requestid", r"awswaf", r"x-amz-cf"],
    "Imperva":        [r"x-iinfo", r"incap_ses", r"visid_incap", r"x-cdn=imperva"],
    "ModSecurity":    [r"mod_security", r"modsecurity"],
    "F5 BIG-IP":      [r"bigipserver", r"f5-bigip", r"x-wa-info"],
    "Barracuda":      [r"barra_counter_session", r"barracuda"],
    "Sucuri":         [r"x-sucuri-id", r"sucuri"],
    "Fastly":         [r"x-served-by.*cache", r"fastly"],
    "Nginx WAF":      [r"naxsi"],
}

_TECH_SIGNATURES = {
    "WordPress":    [r"wp-content/", r"wp-includes/", r"wordpress"],
    "Drupal":       [r"drupal", r"x-drupal-cache", r"x-generator.*drupal"],
    "Joomla":       [r"joomla", r"/components/com_"],
    "Laravel":      [r"laravel_session", r"x-powered-by.*laravel"],
    "Django":       [r"csrfmiddlewaretoken", r"x-powered-by.*django", r"django"],
    "Rails":        [r"x-runtime", r"x-powered-by.*phusion passenger", r"_rails"],
    "ASP.NET":      [r"asp\.net", r"x-aspnet-version", r"x-aspnetmvc-version", r"\.aspx"],
    "Spring":       [r"spring", r"x-application-context"],
    "Express/Node": [r"x-powered-by.*express", r"x-powered-by.*node"],
    "PHP":          [r"x-powered-by.*php", r"\.php"],
    "Apache":       [r"server.*apache"],
    "Nginx":        [r"server.*nginx"],
    "IIS":          [r"server.*iis", r"x-powered-by.*asp"],
    "Tomcat":       [r"server.*tomcat", r"x-powered-by.*servlet"],
}

_DOM_XSS_SINKS = [
    (r"innerHTML\s*=",              "innerHTML assignment"),
    (r"outerHTML\s*=",              "outerHTML assignment"),
    (r"document\.write\s*\(",       "document.write()"),
    (r"document\.writeln\s*\(",     "document.writeln()"),
    (r"\beval\s*\(",                "eval()"),
    (r"setTimeout\s*\(\s*['\"]",    "setTimeout with string argument"),
    (r"setInterval\s*\(\s*['\"]",   "setInterval with string argument"),
    (r"location\.href\s*=",         "location.href assignment"),
    (r"location\.replace\s*\(",     "location.replace()"),
    (r"location\s*=\s*[^=]",       "location assignment"),
    (r"insertAdjacentHTML\s*\(",    "insertAdjacentHTML()"),
    (r"new\s+Function\s*\(",        "new Function() constructor"),
    (r"\$\s*\(\s*['\"][^'\"]*<",    "jQuery HTML injection pattern"),
    (r"\.html\s*\(",                "jQuery .html() sink"),
    (r"postMessage\s*\(",           "postMessage (cross-origin messaging)"),
    (r"window\.name",               "window.name source"),
    (r"document\.referrer",         "document.referrer source"),
    (r"location\.hash",             "location.hash source"),
    (r"location\.search",           "location.search source"),
]

_CSP_JSONP_BYPASS_HOSTS = [
    "accounts.google.com",
    "apis.google.com",
    "ajax.googleapis.com",
    "cdn.jsdelivr.net",
    "unpkg.com",
    "cdnjs.cloudflare.com",
    "code.jquery.com",
    "maxcdn.bootstrapcdn.com",
]

_TAKEOVER_CNAME_SIGNATURES = {
    "GitHub Pages":   r"There isn't a GitHub Pages site here",
    "Heroku":         r"No such app|herokucdn\.com",
    "AWS S3":         r"NoSuchBucket|The specified bucket does not exist",
    "Azure":          r"404 Web Site not found",
    "Shopify":        r"Sorry, this shop is currently unavailable",
    "Fastly":         r"Fastly error: unknown domain",
    "Zendesk":        r"Help Center Closed",
    "Tumblr":         r"Whatever you were looking for doesn't live here",
    "Ghost":          r"The thing you were looking for is no longer here",
    "Netlify":        r"Not Found - Request ID",
    "Surge.sh":       r"project not found",
    "Readme.io":      r"Project doesnt exist",
    "UserVoice":      r"This UserVoice subdomain is currently available",
}

_KNOWN_CAUSAL_SIGS: List[Dict] = [
    {"pk": ["id","uid","user_id","userid","object_id"],
     "tf": "status",   "min_te": 0.06, "dir": "within",
     "vc": "IDOR", "mitre": "COLLECTION"},
    {"pk": ["role","admin","privilege","access","group"],
     "tf": "status",   "min_te": 0.08, "dir": "within",
     "vc": "BROKEN_AC", "mitre": "PRIVILEGE_ESCALATION"},
    {"pk": ["id","uid","user_id"],
     "tf": "list_n",   "min_te": 0.07, "dir": "within",
     "vc": "IDOR_DATA", "mitre": "COLLECTION"},
    {"pk": [], "tf": "", "min_te": 0.04, "dir": "cross_session",
     "vc": "CROSS_SESSION_LEAK", "mitre": "COLLECTION"},
    {"pk": [], "tf": "t_us", "min_te": 0.10, "dir": "within",
     "vc": "BLIND_INJECTION", "mitre": "INITIAL_ACCESS"},
    {"pk": [], "tf": "cr",   "min_te": 0.08, "dir": "within",
     "vc": "RESPONSE_ENTROPY_MANIPULATION", "mitre": "DISCOVERY"},
    {"pk": [], "tf": "status", "min_te": 0.05, "dir": "temporal",
     "vc": "TOCTOU", "mitre": "EXECUTION"},
]

_LING_SIBLING_MAP: Dict[str, List[str]] = {
    "users":    ["admins", "staff", "internal", "debug"],
    "user":     ["admin", "staff", "superuser"],
    "posts":    ["drafts", "unpublished", "deleted"],
    "orders":   ["pending", "internal", "admin"],
    "accounts": ["billing", "admin", "internal"],
    "files":    ["uploads", "private", "admin"],
    "api":      ["internal", "admin", "debug", "v0"],
    "v1":       ["v0", "internal", "admin", "debug"],
    "items":    ["admin", "internal", "deleted"],
}

_VENDOR_SIGS: Dict[str, Tuple[str, str]] = {
    "ollama":      (r'"models"\s*:\s*\[|"name"\s*:\s*"llama|mistral|gemma|phi|qwen"', "/api/tags"),
    "openai":      (r'"object"\s*:\s*"model"|"owned_by"\s*:',                          "/v1/models"),
    "vllm":        (r'max_model_len|vllm|"max_num_seqs"',                              "/v1/models"),
    "tgi":         (r'"model_id"|"max_input_length"|"sha"',                            "/info"),
    "lmstudio":    (r'lm.studio|LM Studio|"mlx"',                                     "/v1/models"),
    "anthropic":   (r'"type"\s*:\s*"message"|"stop_reason"|"input_tokens"',           "/v1/messages"),
    "mistral":     (r'mistral|mixtral|"fim_completion"',                               "/v1/models"),
    "cohere":      (r'"generation_id"|"finish_reason"\s*:\s*"COMPLETE"',              "/v1/generate"),
    "groq":        (r'"x-groq"|"context_window"\s*:\s*\d{4,}',                       "/v1/models"),
    "deepseek":    (r'deepseek|"reasoning_content"',                                  "/v1/models"),
    "localai":     (r'localai|"gpu_layers"|"mmap"',                                   "/v1/models"),
    "dify":        (r'"app_id"|"conversation_id"|"dify"',                             "/v1/apps"),
    "flowise":     (r'"chatflowId"|"flowise"',                                        "/api/v1/chatflows"),
    "openwebui":   (r'open.?webui|"pipeline"',                                        "/api/models"),
    "anythingllm": (r'anythingllm|"workspace"\s*:\s*\{|"slug"\s*:',                  "/api/v1/workspaces"),
}

_LLM_VENDOR_PATHS: Dict[str, List[str]] = {
    "chat": [
        "/v1/chat/completions", "/v1/messages", "/v1/completions",
        "/api/chat", "/api/chat/completions", "/api/completions",
        "/api/generate", "/api/v1/chat", "/api/v1/completions",
        "/api/v1/generate", "/api/v2/chat", "/ask", "/query",
        "/api/message", "/api/messages", "/api/assistant", "/api/ai/chat",
        "/ai/chat", "/llm/chat", "/inference", "/api/inference",
        "/copilot/chat", "/assistant/chat", "/bot/message",
        "/v1/chat-messages", "/api/v1/prediction",
    ],
    "models": [
        "/v1/models", "/api/tags", "/api/ps", "/openai/models",
        "/api/models", "/api/v1/models",
    ],
    "embeddings": [
        "/v1/embeddings", "/api/embeddings", "/api/embed", "/api/encode",
        "/v1/embed", "/embeddings",
    ],
    "config": [
        "/api/config", "/api/settings", "/v1/config", "/config", "/settings",
        "/api/v1/config", "/api/v1/settings", "/api/v1/system",
        "/v1/app-config", "/v1/parameters", "/api/v1/chatflows",
        "/api/workspace/system-prompt",
    ],
    "admin": [
        "/api/v1/credentials", "/api/v1/variables", "/api/v1/admin/users",
        "/api/v1/admin/system", "/api/auths", "/api/users",
    ],
    "agent": [
        "/api/v1/run", "/api/agents", "/api/workflow/run",
        "/api/autopilot", "/api/plan", "/v1/assistants", "/v1/threads",
    ],
    "rag": [
        "/api/upload", "/api/documents", "/api/knowledge", "/api/files",
        "/api/ingest", "/api/index", "/api/search", "/api/retrieve", "/api/context",
        "/api/v1/collections", "/collections", "/v1/schema", "/v1/vector/collections",
    ],
    "mcp": [
        "/mcp", "/mcp/v1", "/.well-known/mcp", "/api/mcp",
        "/mcp/tools", "/mcp/resources", "/mcp/prompts", "/sse", "/mcp/sse",
    ],
}

_ERROR_TOKENS: Dict[str, List[str]] = {
    "stack-trace-leaky": [
        "traceback", "stack trace", "at line", "file \"/", "exception in thread",
        "php fatal error", "notice:", "warning:", "syntaxerror", "referenceerror",
        "typeerror", "valueerror", "nullpointerexception", "stackoverflowerror",
        "at java.", "at org.", "at com.", "errno", "segfault", "coredump",
        "sql error", "syntax error in", "uncaught", "undefined method",
    ],
    "waf-generated": [
        "access denied", "request blocked", "security violation", "mod_security",
        "cloudflare", "you have been blocked", "waf", "firewall", "ddos protection",
        "attention required", "one more step", "checking your browser",
    ],
    "framework-default": [
        "whoa, looks like something went wrong", "internal server error",
        "this page isn't working", "500 internal server error",
        "application error", "nginx error", "apache error",
        "werkzeug debugger", "rails oops", "laravel whoops",
        "django traceback", "express crash", "panic: runtime error",
    ],
    "sanitized-production": [
        "an error occurred", "something went wrong", "please try again",
        "contact support", "error id:", "reference number",
    ],
    "custom-opaque": [],
}

_FAVICON_HASHES: Dict[str, str] = {
    "708578f7": "Apache (default favicon)",
    "99395a5c": "Nginx (default favicon)",
    "8c6a025d": "IIS (default favicon)",
    "f7dcb571": "WordPress",
    "e6847b9e": "Drupal",
    "2d3b82e3": "Joomla",
    "7d037b73": "Tomcat",
    "35e9b767": "Jenkins",
    "7ba2bad7": "GitLab",
    "21a1e83a": "Confluence",
    "4a5a9f78": "Kibana",
    "589a8b8c": "Grafana",
    "c0d0d748": "phpMyAdmin",
    "78abe92a": "Fortinet FortiGate",
    "a6b8f31b": "Palo Alto GlobalProtect",
    "1f69c527": "Citrix NetScaler",
}

__all__ = [
    "_JS_LIB_CVES",
    "_STACK_SIGNALS",
    "_KEV_META",
    "_SENSITIVE_PATHS",
    "_SQL_ERRORS",
    "_ERROR_DISCLOSURE",
    "_NOSQL_ERRORS",
    "_WAF_SIGNATURES",
    "_TECH_SIGNATURES",
    "_DOM_XSS_SINKS",
    "_CSP_JSONP_BYPASS_HOSTS",
    "_TAKEOVER_CNAME_SIGNATURES",
    "_KNOWN_CAUSAL_SIGS",
    "_LING_SIBLING_MAP",
    "_VENDOR_SIGS",
    "_LLM_VENDOR_PATHS",
    "_ERROR_TOKENS",
    "_FAVICON_HASHES",
]
